export function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
}
export const discoveryMessage = 'Keeply helps you remember all kinds of important dates, from payments and renewals to appointments and personal plans. Explore our categories or create your own reminder.';
export function emailLink(href: string, label: string) {
  return '<a href="' + escapeHtml(href) + '" style="color:#5143ad;text-decoration:underline">' + escapeHtml(label) + '</a>';
}
export function emailButton(href: string, label: string) {
  return '<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:24px 0"><tr><td bgcolor="#6153ca" style="border-radius:12px;text-align:center"><a href="' + escapeHtml(href) + '" style="display:inline-block;border:1px solid #6153ca;border-radius:12px;padding:14px 24px;font-size:16px;line-height:22px;font-weight:700;color:#ffffff;text-decoration:none">' + escapeHtml(label) + '</a></td></tr></table>';
}
export function emailPanel(label: string, title: string, detail: string) {
  return '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td bgcolor="#f3effc" style="padding:24px;border:1px solid #e4ddf4;border-radius:14px"><p style="margin:0 0 8px;font-size:12px;letter-spacing:1px;text-transform:uppercase;color:#655e73">' + escapeHtml(label) + '</p><p style="margin:0 0 8px;font-size:22px;line-height:1.4;font-weight:700;overflow-wrap:anywhere">' + escapeHtml(title) + '</p><p style="margin:0;font-size:16px;color:#51465f">' + escapeHtml(detail) + '</p></td></tr></table>';
}
export function discoveryText(url: string) {
  return discoveryMessage + '\nExplore categories: ' + url + '/add\nCreate your own: ' + url + '/add/other';
}
export function emailLayout(input: { url: string; preview: string; eyebrow: string; heading: string; body: string; reason: string; unsubscribe?: string }) {
  const e = escapeHtml, link = emailLink;
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>Keeply</title></head><body style="margin:0;padding:0;background:#f5f3f9;color:#292639;font-family:Arial,Helvetica,sans-serif;line-height:1.65"><div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all">' + e(input.preview) + '</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#f5f3f9"><tr><td align="center" style="padding:32px 12px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" border="0" bgcolor="#ffffff" style="width:100%;max-width:600px;border:1px solid #e6e0ef;border-radius:20px"><tr><td style="padding:32px 28px 24px;border-bottom:1px solid #eee9f4"><table role="presentation" cellspacing="0" cellpadding="0" border="0"><tr><td width="48" style="padding-right:12px"><img src="' + e(input.url + '/brand/keeply-logo.png') + '" width="44" height="44" alt="" style="display:block;border:0"></td><td><a href="' + e(input.url) + '" style="color:#292639;text-decoration:none;font-size:27px;line-height:1.2;font-weight:700">keeply<span style="color:#6153ca">.</span></a></td></tr></table><p style="margin:12px 0 0;font-size:13px;color:#655e73">Your household, a little more organised.</p></td></tr><tr><td style="padding:28px"><p style="margin:0 0 10px;font-size:12px;font-weight:700;letter-spacing:1.4px;text-transform:uppercase;color:#6153ca">' + e(input.eyebrow) + '</p><h1 style="margin:0 0 24px;font-size:28px;line-height:1.25;letter-spacing:-.5px">' + e(input.heading) + '</h1>' + input.body + '</td></tr><tr><td bgcolor="#faf8fe" style="padding:24px 28px;border-top:1px solid #eee9f4;border-radius:0 0 18px 18px"><p style="margin:0 0 8px;font-size:15px;font-weight:700">A place for every important date.</p><p style="margin:0;font-size:14px;color:#655e73">Keeply helps you remember all kinds of important dates, from payments and renewals to appointments and personal plans. ' + link(input.url + '/add', 'Explore our categories') + ' or ' + link(input.url + '/add/other', 'create your own reminder') + '.</p></td></tr></table><table role="presentation" width="600" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:600px"><tr><td style="padding:20px 16px;text-align:center;font-size:12px;line-height:1.7;color:#655e73"><p style="margin:0 0 8px">' + e(input.reason) + '</p><p style="margin:0">' + link(input.url + '/settings/alerts', 'Manage email preferences') + (input.unsubscribe ? ' &nbsp;·&nbsp; ' + link(input.unsubscribe, 'Unsubscribe from ideas & tips') : '') + '</p><p style="margin:8px 0 0">Keeply · Little things, safely kept.</p></td></tr></table></td></tr></table></body></html>';
}
