import { emailButton, emailLayout, emailLink, escapeHtml } from './email-layout';
import { formatDate, formatMoney } from './domain';
export interface HouseholdEmailRow {job_id:string;item_id:string;date_id:string;product_name:string;label:string;due_on:string;amount_minor:number|null;certainty:string|null;scheduled_on:string}
export function householdEmail(input:{from:string;to:string;url:string;rows:HouseholdEmailRow[]}) {
 const rows=input.rows.slice(0,20),extra=input.rows.length-rows.length;
 const description=(row:HouseholdEmailRow)=>`${row.product_name}: ${row.label}, ${formatDate(row.due_on,true)}${row.amount_minor==null?'':', '+formatMoney(row.amount_minor)+(row.certainty==='estimated'?' (estimate)':'')}`;
 const subject=`Your household heads-up: ${input.rows.length} ${input.rows.length===1?'date':'dates'} to review`;
 const text=rows.map(row=>description(row)+'\n'+input.url+'/items/'+row.item_id+'#date-'+row.date_id).join('\n\n');
 const body=rows.map(row=>'<div style="padding:16px 0;border-bottom:1px solid #eee9f4"><p style="margin:0;font-weight:700">'+escapeHtml(row.product_name)+'</p><p style="margin:5px 0">'+escapeHtml(row.label)+' · '+escapeHtml(formatDate(row.due_on,true))+'</p>'+(row.amount_minor==null?'':'<p style="margin:5px 0">'+escapeHtml(formatMoney(row.amount_minor))+(row.certainty==='estimated'?' (estimate)':'')+'</p>')+emailLink(input.url+'/items/'+row.item_id+'#date-'+row.date_id,'Review this record')+'</div>').join('');
 return {from:input.from,to:input.to,subject,text:text+(extra?`\n\nPlus ${extra} more dates in your household overview.`:'')+'\n\nReview your household: '+input.url+'/dashboard\nThese reminders follow your chosen timings. They do not confirm payments or appointments.\nEmail preferences: '+input.url+'/settings/alerts',html:emailLayout({url:input.url,preview:subject,eyebrow:'YOUR HOUSEHOLD, IN SIGHT',heading:'A little heads-up for your household.',body:'<p>Your chosen reminders, together in one place.</p>'+body+(extra?'<p>Plus '+extra+' more dates in your household overview.</p>':'')+emailButton(input.url+'/dashboard','Review my household')+'<p style="font-size:13px;color:#655e73">Based on your saved dates and selected alert timings. This email does not confirm payments or appointments.</p>',reason:'You received this household email because alerts are enabled for these dates. Manage your preferences in Alert Options.'})};
}
