import { TrackerPage } from '@/components/tracker-page';
export const metadata={title:'Car & motorcycle registration alerts Philippines',description:'Remember user-confirmed vehicle registration, insurance renewal and service dates with Keeply. Car and motorcycle templates, optional email alerts.',alternates:{canonical:'/vehicle-registration-reminder'}};
export default function Page(){return <TrackerPage page="vehicle-registration-reminder" title="Your next renewal, remembered." intro="One place for your car or motorcycle’s registration, insurance and service dates. Add the deadline you’ve confirmed, then choose a heads-up." example="My Toyota Vios · Registration · 27 days remaining. Insurance and the next service can have their own dates on the same vehicle." sections={[
{id:'car',title:'A place for your car’s dates',body:'Start with a nickname such as My Vios. Add a registration date confirmed from current documents or with LTO. Proposed emails are 30, 7 and 1 day before; adjust or leave emails off. A full plate number is not required.',cta:'Track my car',href:'/add/car?focus=registration'},
{id:'renewal-guide',title:'Prepare for your LTO registration renewal',body:'Read the requirements, check the standard plate-based schedule, and compare online and walk-in renewal steps in our sourced guide.',cta:'Read the LTO renewal guide',href:'/lto-registration-renewal'},
{id:'motorcycle',title:'Motorcycle renewals deserve a little room, too',body:'Use the Motorcycle template for your registration, policy renewal and maintenance dates. Keep optional OR/CR or receipts with the vehicle. Upload only what you need; these documents can contain personal information.',cta:'Track my motorcycle',href:'/add/motorcycle?focus=registration'},
{id:'insurance',title:'Remember vehicle insurance renewal',body:'Insurance is a separate date on your vehicle, so one policy renewal does not overwrite registration. Open an existing vehicle and choose Add a date → Insurance renewal. If starting fresh, choose your vehicle type below.',cta:'Choose my vehicle',href:'/add'},
{id:'service',title:'Remember the service, keep the history',body:'Record the next service date. On completion, enter when it was done and confirm the next date. Where you’ve chosen a maintenance interval, calculate from completion or keep the original schedule. Keeply does not prescribe a universal PMS interval.',cta:'Add my vehicle',href:'/add'}
]} checklist={['A helpful vehicle nickname; no full plate number needed.','Confirm the current deadline with your documents or LTO, including any applicable exceptions.','Optional OR/CR, insurance document or service receipt.','Registration, insurance and service on the same vehicle share one alert slot.']} limitations="Keeply is not an LTO service and does not renew registration or calculate deadlines from your plate. Confirm current requirements at lto.gov.ph. Insurance alerts do not validate coverage, and service timing should follow the manufacturer or technician."/>;}
