import Link from 'next/link';
import { Check } from 'lucide-react';
import { Brand } from '@/components/brand';
export const metadata = {
  title: 'Pricing — free alerts & extra slots',
  description: 'Save unlimited reminders with 3 free alert slots. Add 5 slots for ₱29 per 30 days or ₱249 once. Manual renewal, no automatic charges.',
  alternates: { canonical: '/pricing' },
};
export default function PricingPage() { return <><nav className="public-nav"><Brand /><Link href="/add" className="button primary">Get started</Link></nav><main className="landing" id="main-content"><div className="landing-hero"><div className="eyebrow">SIMPLE PLANS. LESS TO THINK ABOUT.</div><h1>Start small.<br /><em>Keep a little more.</em></h1><p>Keep as many things as you need. Your first 3 alert slots are free.</p></div><div className="pricing-grid">
  {[{ name: 'Free', price: '₱0', period: 'to start', list: ['Unlimited saved reminders', '3 alert slots', '100 MB of private file storage'], action: 'Start for free' }, { name: '+5 alert slots', price: '₱29', period: 'for 30 days', list: ['8 total alert slots', 'Renew manually through PayMongo', 'No automatic charges'], action: 'Create your account' }, { name: '+5 permanent slots', price: '₱249', period: 'once', list: ['8 total alert slots', 'Five extra slots permanently', 'One payment'], action: 'Create your account' }].map(plan => <section className="panel plan-card" key={plan.name}><h2>{plan.name}</h2><div className="plan-price">{plan.price} <small>{plan.period}</small></div><ul className="plan-list">{plan.list.map(t => <li key={t}><Check size={16} />{t}</li>)}</ul><Link href="/add" className={'button wide ' + (plan.name !== 'Free' ? 'primary' : 'secondary')}>{plan.action}</Link></section>)}</div><p className="privacy-note">All enabled dates on a reminder share one slot. File-enabled templates support up to 6 files, 10 MB each. Alert packs do not add file storage. Prices in Philippine pesos.</p><p className="hint centered">Alerts are a helpful nudge, not a guarantee of coverage. Check the seller’s warranty terms.</p></main></>; }
