import { IdCategory } from '@/components/id-category';
import { headers } from 'next/headers';
import { PublicMetrics } from '@/components/public-metrics';
import Link from 'next/link';
import { ArrowRight, Camera, ShieldCheck, Bell } from 'lucide-react';
import { Brand } from '@/components/brand';
import { TemplateIcon, ReminderIcon } from '@/components/reminder-icon';
import { AlertIndicator } from '@/components/alert-indicator';
import { templateKeys, templates } from '@/features/templates';
const title = 'All-in-One Bill, Warranty & ID Reminders';
const description = 'One place for bills, warranties, IDs, passports and any important date. Keeply PH helps you remember car payments, renewals and more. Start free.';
export const metadata = {
  title, description, alternates: { canonical: '/' },
  openGraph: { title: title + ' · Keeply PH', description, url: '/', siteName: 'Keeply PH', locale: 'en_PH', type: 'website' },
  twitter: { card: 'summary_large_image', title: title + ' · Keeply PH', description },
};
export default async function HomePage(){const nonce=(await headers()).get('x-nonce') || undefined;return <><script type="application/ld+json" nonce={nonce} dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'WebSite','name':'Keeply PH','url':'https://www.keeplyph.com','inLanguage':'en-PH'},{'@type':'WebApplication','name':'Keeply','url':'https://www.keeplyph.com','applicationCategory':'LifestyleApplication','operatingSystem':'Web browser','description':description,'featureList':['Warranty and appliance reminders','Car payment and renewal reminders','ID and passport date reminders','NBI and Police Clearance reminders','Water and electric bill reminders','Optional email alerts'],'inLanguage':'en-PH'}]}).replace(/</g,'\u003c')}}/><PublicMetrics page="home"/><nav className="public-nav"><Brand/><div><Link href="#how-it-works">How it works</Link><Link href="/pricing">Pricing</Link><Link className="button secondary" href="/login">Sign in <ArrowRight size={15}/></Link></div></nav><main className="landing landing-home" id="main-content">
<section className="landing-hero"><div className="eyebrow">WARRANTIES, BILLS & IMPORTANT DATES</div><h1>All your reminders.<br/><em>One easy place.</em></h1><p>From appliance warranties and car payments to IDs, passports, water bills, electric bills and any other important date—Keeply brings your easy-to-forget dates together, with email reminders you choose.</p><div className="hero-actions"><Link className="button primary" href="/add">Start for free <ArrowRight size={17} aria-hidden="true"/></Link><Link className="button secondary" href="/demo">See an example</Link></div><p className="hero-footnote">Save unlimited reminders. Get alerts for 3 reminders free.<br/>No credit card required.</p></section>
<section className="category-section"><h2>What should Keeply remember for you?</h2><p className="section-description">For busy households, car owners and anyone with one too many dates to remember.</p><div className="category-grid"><IdCategory card /><IdCategory card group="clearances" />{([
['receipt','Receipts & warranties','Keep purchase receipts and warranty end dates together.','/warranty-tracker'],
['receipt','Appliance warranties','Remember coverage for your fridge, washer and other appliances.','/add/receipt?focus=warranty&category=appliances'],
['car','Car payments','Keep your next loan installment or vehicle bill in view.','/add/other?preset=car-payment'],
['car','Vehicle renewals','Registration, insurance and maintenance for cars and motorcycles.','/vehicle-registration-reminder'],
['passport','Passports','Get a heads-up before your printed expiration date.','/add/passport'],
['other','Water bills','Remember the payment deadline on your water bill.','/add/other?preset=water-bill'],
['other','Electric bills','Keep your electricity bill due date on your radar.','/add/other?preset=electric-bill'],
['other','Anything else','Subscriptions, appointments, memberships or any date that matters to you.','/add/other'],
] as const).map(([type,label,description,href])=><Link key={label} href={href} className="category-card"><ReminderIcon template={type}/><strong>{label}<ArrowRight size={17} aria-hidden="true"/></strong><p>{description}</p></Link>)}</div><Link className="text-button" href="#everything">See everything Keeply can track →</Link></section>
<section className="landing-preview"><div className="section-heading"><h2>A little heads-up</h2><span className="badge none">Example</span></div><div className="example-dates">{([['receipt','Sony headphones','Warranty','11 days remaining',true],['car','Toyota Vios','Registration','27 days remaining',true],['passport','My passport','Expiration','8 months remaining · Later',false]] as const).map(([type,name,kind,time,alerts])=><div key={name}><ReminderIcon template={type} size={20}/><span><strong className="reminder-name">{name}{alerts && <AlertIndicator status="enabled"/>}</strong><small>{kind}</small></span><span>{time}</span></div>)}</div><Link className="text-button spaced" href="/demo">Explore a sample account →</Link></section>
<section id="how-it-works" className="landing-features"><div><Camera size={25}/><h3>Choose what you want to keep.</h3><p>Choose a warranty, bill, ID or renewal. Start with the date you forget most often.</p></div><div><Bell size={25}/><h3>Add the details that matter.</h3><p>Save a document where supported, add a date, and choose whether you want email alerts.</p></div><div><ShieldCheck size={25}/><h3>Find it when you need it.</h3><p>Your reminders and files are private to your account. Google sign-in keeps getting back to them simple.</p></div></section>
<section id="home-appliances" className="panel space-bottom"><h2>Appliance warranties and household bills, together.</h2><p className="section-description">Save the warranty for a new fridge, plan an aircon clean, and add the due dates from your water and electric bills. Keeply gives those household deadlines a home.</p><div className="hero-actions spaced"><Link className="button secondary" href="/add/receipt?category=appliances">Keep an appliance receipt</Link><Link className="button secondary" href="/add/aircon">Remember an aircon clean</Link></div></section>
<section id="everything" className="category-section"><h2>Everything Keeply can track</h2><p className="section-description">These are just starting points. Add a custom reminder for subscriptions, appointments, memberships or anything else you want to remember.</p><div className="home-template-directory">{templateKeys.map(key => <Link key={key} href={"/add/" + key}><TemplateIcon template={key}/><span><strong>{templates[key].label}</strong><small>{templates[key].description}</small></span><ArrowRight size={17} aria-hidden="true"/></Link>)}</div></section>
<section className="panel"><h2>A little room, for free.</h2><p className="spaced">Keep as many things as you need. No credit card required.</p><p className="section-description">Your first 3 alert slots are free, with 100 MB of documents. All enabled dates on a reminder share one alert slot.</p><Link className="text-button spaced" href="/pricing">See alert packs →</Link></section>
<section className="public-faq"><h2>Your reminder questions, answered</h2><details><summary>What can I keep in this all-in-one reminder app?</summary><p>Track purchase and appliance warranties, car payments, vehicle registration and insurance, Driver’s License and passport expiration, PRC License, Postal ID, PWD / Solo Parent ID and other ID dates, NBI and Police Clearance dates, and water and electric bill deadlines. You can also create a custom reminder for any other important date.</p></details><details><summary>Can I set reminders for water, electric and car bills?</summary><p>Yes. Choose a bill category, enter the due date shown on your bill and opt into email alerts. After paying, mark the date done and add the next due date. Keeply does not pay bills or import billing schedules.</p></details><details><summary>What date should I use for an ID or clearance?</summary><p>Use the expiration date printed on your document when applicable, or choose a renewal appointment, update or follow-up date. Keeply does not assume a validity period.</p></details><details><summary>Do I need to upload an ID?</summary><p>No. ID, passport and clearance reminders only need a helpful name and your chosen date. Do not include scans or identity numbers.</p></details><details><summary>Are alerts automatic?</summary><p>You choose whether to receive emails for each date. Proposed timings are editable. Alert delivery also follows your account preferences.</p></details><details><summary>Can Keeply renew my documents?</summary><p>Keeply helps you remember and organise. Confirm official deadlines and complete renewals with the responsible provider or agency.</p></details><details><summary>Can I delete what I’ve saved?</summary><p>Yes. You can remove a reminder or request account deletion in Settings. See the privacy policy for file cleanup and backup limits.</p></details></section>
<section className="home-final-cta"><h2>Start with one thing.</h2><p>Your next bill, warranty or renewal can be one less thing on your mind.</p><Link className="button primary" href="/add">Start for free <ArrowRight size={17} aria-hidden="true"/></Link></section></main><footer className="app-footer"><span>Little things, safely kept.</span><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/pricing">Pricing</Link><Link href="/privacy#contact">Contact</Link><Link href="/feedback">Feedback</Link></div></footer></>;}
