import { headers } from 'next/headers';
import { PublicMetrics } from '@/components/public-metrics';
import Link from 'next/link';
import { ArrowRight, Camera, ShieldCheck, Bell } from 'lucide-react';
import { Brand } from '@/components/brand';
import { TemplateChoices } from '@/components/template-picker';
export const metadata={alternates:{canonical:'/'}};
export default async function HomePage(){const nonce=(await headers()).get('x-nonce') || undefined;return <><script type="application/ld+json" nonce={nonce} dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'WebSite','name':'Keeply PH','url':'https://www.keeplyph.com','inLanguage':'en-PH'},{'@type':'WebApplication','name':'Keeply','url':'https://www.keeplyph.com','applicationCategory':'LifestyleApplication','operatingSystem':'Web browser','description':'Private receipts, important dates and optional email reminders.'}]}).replace(/</g,'\u003c')}}/><PublicMetrics page="home"/><nav className="public-nav"><Brand/><div><Link href="#how-it-works">How it works</Link><Link href="/pricing">Pricing</Link><Link className="button secondary" href="/login">Sign in <ArrowRight size={15}/></Link></div></nav><main className="landing" id="main-content">
<section className="landing-hero"><div className="eyebrow">A LITTLE LESS TO REMEMBER</div><h1>Your important things,<br/><em>remembered.</em></h1><p>A home for your receipts, vehicle renewals and document expiry dates. Find what you need, with a little heads-up when it matters.</p><div className="hero-actions"><Link className="button primary" href="/add">Start for free <ArrowRight size={17}/></Link><Link className="button secondary" href="/demo">See an example</Link></div><p className="hero-footnote">Keep as many things as you need. No credit card required.</p></section>
<section className="category-section"><h2>What should Keeply remember for you?</h2><p className="section-description">The little things that deserve a place of their own.</p><div className="category-grid">{[['Receipts & warranties','Find your receipt. Know your coverage.','/warranty-tracker'],['Vehicle documents','Car and motorcycle renewal dates.','/vehicle-registration-reminder'],['IDs & licences','Your driving licence expiry, dates only.','/document-expiry-tracker#drivers-licence'],['Passports','A little more time to plan your renewal.','/document-expiry-tracker#passport'],['Vehicle insurance','Remember your next policy renewal.','/vehicle-registration-reminder#insurance'],['Home & appliances','A warranty receipt or the next aircon clean.','#home-appliances']].map(([label,description,href])=><Link key={label} href={href} className="category-card"><strong>{label}<ArrowRight size={17}/></strong><p>{description}</p></Link>)}</div><Link className="text-button" href="#everything">See everything Keeply can track →</Link></section>
<section className="landing-preview"><div className="section-heading"><h2>A little heads-up</h2><span className="badge none">Example</span></div><div className="example-dates">{[['Sony headphones','Warranty','11 days remaining'],['Toyota Vios','Registration','27 days remaining'],['My passport','Expiration','8 months remaining · Later']].map(([name,kind,time])=><div key={name}><Bell size={20}/><span><strong>{name}</strong><small>{kind}</small></span><span>{time}</span></div>)}</div><Link className="text-button spaced" href="/demo">Explore a sample account →</Link></section>
<section id="how-it-works" className="landing-features"><div><Camera size={25}/><h3>Choose what you want to keep.</h3><p>A purchase, a vehicle, a passport date. Start with one thing.</p></div><div><Bell size={25}/><h3>Add the details that matter.</h3><p>Save a document where supported, add a date, and choose whether you want email reminders.</p></div><div><ShieldCheck size={25}/><h3>Find it when you need it.</h3><p>Your items and files are private to your account. Google sign-in keeps getting back to them simple.</p></div></section>
<section id="home-appliances" className="panel space-bottom"><h2>A calmer home, one small habit at a time.</h2><p className="section-description">Keep appliance receipts with their warranties, or remember the next aircon service.</p><div className="hero-actions spaced"><Link className="button secondary" href="/add/receipt?category=appliances">Keep an appliance receipt</Link><Link className="button secondary" href="/add/aircon">Remember an aircon clean</Link></div></section>
<section id="everything" className="category-section"><h2>Everything Keeply can track</h2><p className="section-description">Practical starting points. No complicated setup.</p><TemplateChoices/></section>
<section className="panel"><h2>A little room, for free.</h2><p className="spaced">Keep as many things as you need. No credit card required.</p><p className="section-description">Your first 3 item reminder slots are free, with 100 MB of documents. All enabled dates on an item share one slot.</p><Link className="text-button spaced" href="/pricing">See reminder packs →</Link></section>
<section className="public-faq"><h2>A few useful details</h2><details><summary>Do I need to upload an ID?</summary><p>No. Passport and driver’s licence templates keep a name and expiry date, without scans or identity numbers.</p></details><details><summary>Are reminders automatic?</summary><p>You choose whether to receive emails for each date. Proposed timings are editable. Reminder delivery also follows your account preferences.</p></details><details><summary>Can Keeply renew my documents?</summary><p>Keeply helps you remember and organise. Confirm official deadlines and complete renewals with the responsible provider or agency.</p></details><details><summary>Can I delete what I’ve saved?</summary><p>Yes. You can remove an item or request account deletion in Settings. See the privacy policy for file cleanup and backup limits.</p></details></section>
</main><footer className="app-footer"><span>Little things, safely kept.</span><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/pricing">Pricing</Link><Link href="/privacy#contact">Contact</Link></div></footer></>;}
