'use client';
import Link from 'next/link';
import { SlotPlans } from './slot-plans';
import { useActionState } from 'react';
import { useRouter } from 'next/navigation';
import { startCheckout } from '@/features/billing/actions';
import { formatDate, formatMoney, type Usage } from '@/lib/domain';
import { capabilities } from '@/features/entitlements/domain';
import { PaymentStatus } from './payment-status';
import type { Product } from '@/features/billing/products';
export interface BillingOrder { id:string;amount_minor:number;currency:string;status:string;created_at:string;period_ends_at:string|null;product?:string;slot_count?:number }
export interface BillingCoverageItem { id: string; product_name: string | null }
export function Billing({usage,orders=[],enabled=false,returned,returnedOrderId,demo=false,testMode=false,methods=[],support='rgianmcabrera@gmail.com',freeCoverage=[],checkoutSlots,preferredProduct}:{usage:Usage;orders?:BillingOrder[];enabled?:boolean;returned?:string;returnedOrderId?:string;demo?:boolean;testMode?:boolean;methods?:string[];support?:string;freeCoverage?:BillingCoverageItem[];checkoutSlots?:number;preferredProduct?:Product}) {
 const [state,action,pending]=useActionState(startCheckout,{});const router=useRouter();const cap=capabilities(usage);
 const temporaryActive=usage.temporary_active ?? cap.slots > 3;
 const freeSlots=3+(usage.bonus_slots??0);
 const returnedOrder = returnedOrderId ? orders.find(order => order.id === returnedOrderId) : undefined;
 const paymentAwaiting = returned === 'return' && returnedOrder?.status === 'pending';
 const slotSummary=demo ? `This sample account has ${cap.slots} alert slots, with ${cap.available} available. New accounts start with 3 free slots.` : usage.permanent ? `Your ${usage.permanent_slots ?? 5} purchased extra slots are permanent.` : temporaryActive && usage.paid_until ? 'Purchased extra slots available through '+formatDate(usage.paid_until)+'. Renew manually whenever you’re ready.' : usage.paid_until ? `Your temporary pack has expired. Your ${freeSlots} free alert slots are still available.` : `Your ${freeSlots} free alert slots are available.`;
 return <><div className="page-heading"><div><div className="eyebrow">A LITTLE MORE ROOM</div><h1>More things can remind you.</h1><p>Keep as many reminders as you need. Choose which ones send alerts.</p></div></div>
 {!demo && (returned==='return'||returned==='cancelled') && <PaymentStatus key={returnedOrder?.id || 'unmatched'} order={returnedOrder} returned={returned} support={support}/>}
 <section className="panel space-bottom"><h2>Your alert slots</h2><p className="expiry-big">{cap.used} of {cap.slots} slots used</p><p className="section-description">{usage.purchases} saved reminders, including archived · Unlimited reminders</p><p className="hint">{slotSummary}</p>{usage.bonus_slots === 2 && <p className="hint spaced">Includes 2 permanent free slots from your one-time installation and notification reward.</p>}<p className="hint spaced">Documents: {Math.ceil(usage.storage_bytes/1048576)} / {Math.round(cap.storageBytes/1048576)} MB. Alert packs do not add file storage.</p><Link className="text-button spaced" href={(demo?'/demo':'')+'/items?filter=reminders'}>Manage alert coverage →</Link><p className="hint spaced">When a pack expires, your oldest selected reminders keep the available slots; extra selections pause. They resume when capacity returns. You can turn coverage off or move it to another reminder.</p></section>
 {temporaryActive && usage.paid_until && !usage.permanent && <section className="panel space-bottom"><h2>If you don’t renew</h2><p className="section-description">Your oldest {freeSlots} selected items keep free coverage. Extra alerts pause, and your saved reminders stay accessible. You can change your selections before expiry.</p>{freeCoverage.length > 0 ? <><p className="hint spaced">Based on your current selections, these items retain coverage:</p><ul className="coverage-retained">{freeCoverage.map(item=><li key={item.id}><Link href={(demo?'/demo':'')+'/items/'+item.id}>{item.product_name || 'Untitled reminder'}</Link></li>)}</ul></> : <p className="hint spaced">No items are currently selected for free coverage.</p>}<Link className="text-button" href={(demo?'/demo':'')+'/items?filter=reminders'}>Choose which items keep alerts →</Link></section>}
 <SlotPlans freeSlots={freeSlots} action={demo ? undefined : action} pending={pending} enabled={enabled && !paymentAwaiting} permanentSlots={usage.permanent ? usage.permanent_slots ?? 5 : 0} initialSlots={checkoutSlots ?? usage.renewal_slots ?? 5} preferredProduct={preferredProduct} paidUntil={!usage.permanent && usage.paid_until && temporaryActive ? usage.paid_until : null}/>
 {paymentAwaiting && <p className="hint spaced">Checkout is paused while this payment awaits confirmation. Use Refresh status above or contact support if you were charged.</p>}
 {!demo&&!enabled&&<p className="hint spaced">Payments will open after checkout setup is complete.</p>}{testMode&&enabled&&<p className="alert info spaced">Test checkout · no live payment</p>}{state.error&&<p className="alert error spaced" role="alert">{state.error}</p>}
 {!demo && enabled && <section className="panel spaced pricing-payment"><h2>Before you pay</h2>{methods.length > 0 && <p>PayMongo checkout · Configured methods: {methods.join(', ')}. Available methods are shown at checkout.</p>}<p>Your button shows the selected quantity and full price in pesos. Access starts after verified payment. Keeply does not store your full card details.</p><Link className="text-button" href="/terms#payment-problems">Payment help &amp; refund requests →</Link></section>}
 <p className="hint spaced">Early renewal adds a 30-day term after your remaining prepaid time. Each term uses the slot count purchased for it. Switching to permanent replaces temporary slots immediately, without an automatic prorated refund. No recurring subscription.</p><Link className="text-button" href={(demo?'/demo':'')+'/settings'}>Choose renewal email preferences →</Link>
 <section className="panel spaced"><div className="section-heading"><h2>Payment history</h2><button className="text-button" onClick={()=>router.refresh()}>Refresh status</button></div>{orders.length?<div className="table-scroll"><table className="billing-table"><thead><tr><th>Date</th><th>Reference</th><th>Pack</th><th>Amount</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{formatDate(o.created_at,true)}</td><td><code>{o.id}</code></td><td>{o.product==='legacy_year'?'Annual access':o.slot_count?`${o.slot_count} slots · ${o.product==='slots_permanent'?'Permanent':'30 days'}`:'Alert pack'}</td><td>{formatMoney(o.amount_minor)}</td><td>{o.status==='review'?'Under review':o.status}</td></tr>)}</tbody></table></div>:<p className="section-description">No payments yet.</p>}</section></>;
}
