'use client';
import Link from 'next/link';
import { useActionState } from 'react';
import { useRouter } from 'next/navigation';
import { startCheckout } from '@/features/billing/actions';
import { formatDate, formatMoney, type Usage } from '@/lib/domain';
import { PaymentStatus } from './payment-status';
import { PremiumPlans } from './premium-plans';
export interface BillingOrder {id:string;amount_minor:number;currency:string;status:string;created_at:string;period_ends_at:string|null;product?:string;slot_count?:number;can_resume?:boolean}
export function Billing({usage,orders=[],enabled=false,returned,returnedOrderId,demo=false,testMode=false,support='rgianmcabrera@gmail.com',timezone='Asia/Manila',pendingOrderId}:{usage:Usage;orders?:BillingOrder[];enabled?:boolean;returned?:string;returnedOrderId?:string;demo?:boolean;testMode?:boolean;methods?:string[];support?:string;timezone?:string;pendingOrderId?:string}) {
 const [state,action,pending]=useActionState(startCheckout,{}),router=useRouter();
 const order=returnedOrderId?orders.find(entry=>entry.id===returnedOrderId):undefined,awaiting=pendingOrderId?orders.find(entry=>entry.id===pendingOrderId):undefined;
 return <><div className="page-heading"><div><span className="eyebrow">A LITTLE MORE BREATHING ROOM</span><h1>Ease into the months ahead.</h1><p>Keeply Premium brings your saved household obligations into a longer view.</p></div></div>
 {!demo&&(returned==='return'||returned==='cancelled')&&<PaymentStatus order={order} returned={returned} support={support}/>}
 <section className="panel space-bottom"><h2>{demo?'Explore the Premium sample':usage.household_premium?'Your Premium is active':'Your household account'}</h2><p className="section-description">{demo?'Try a year of sample bills, maintenance and renewals.':usage.permanent&&usage.household_premium?'Your existing permanent purchase includes household Premium while Keeply operates.':usage.household_premium_until&&usage.household_premium?'Premium available until '+new Intl.DateTimeFormat('en-PH',{dateStyle:'medium',timeStyle:'short',timeZone:timezone}).format(new Date(usage.household_premium_until))+' ('+timezone+').':usage.household_premium?'Your existing purchase includes household Premium.':'Your saved records, history, alerts and next 30 days remain available.'}</p><Link className="button secondary spaced" href={(demo?'/demo':'')+'/planner?days='+(demo||usage.household_premium?'365':'30')}>Open household planner →</Link><p className="hint spaced">Documents: {Math.ceil(usage.storage_bytes/1048576)} / {Math.round((usage.storage_limit_bytes??104857600)/1048576)} MB. Household Premium does not increase file storage.</p></section>
 {!usage.installation_premium_claimed&&!demo&&<section className="panel space-bottom"><h2>Install Keeply. Enjoy 30 days of full Premium.</h2><p className="section-description">No card. No payment details. No automatic charges. Open the installed app while signed in and your gift activates automatically, once per account.</p><Link className="text-button spaced" href="/settings/alerts">Show me how to install →</Link></section>}
 <PremiumPlans action={demo?undefined:action} pending={pending} enabled={enabled} awaitingProduct={awaiting?.product}/>
 {!demo&&!enabled&&<p className="hint spaced">Paid Premium plans are temporarily unavailable. You can use your account and claim the installation gift without payment details.</p>}{awaiting&&<p className="alert info spaced">A payment is awaiting confirmation. Review its status in your history before paying again.</p>}{testMode&&enabled&&<p className="alert info spaced">Test checkout. No live payment.</p>}{state.error&&<p className="alert error spaced" role="alert">{state.error}</p>}
 <p className="hint spaced">Paid time starts after any remaining Premium time. Every purchase is a separate verified PayMongo checkout. No automatic renewal. When Premium ends, your records and core alerts stay available.</p>
 <section className="panel spaced"><div className="section-heading"><h2>Payment history</h2><button className="text-button" onClick={()=>router.refresh()}>Refresh status</button></div>{orders.length?<div className="table-scroll"><table className="billing-table"><thead><tr><th>Date</th><th>Reference</th><th>Purchase</th><th>Amount</th><th>Status</th></tr></thead><tbody>{orders.map(entry=><tr key={entry.id}><td>{formatDate(entry.created_at,true)}</td><td><code>{entry.id}</code></td><td>{entry.product==='premium_year'?'Premium · One year':entry.product==='premium_30'?'Premium · 30 days':entry.product==='legacy_year'?'Historical annual access':`${entry.slot_count??5} historical alert slots`}</td><td>{formatMoney(entry.amount_minor)}</td><td>{entry.status==='review'?'Under review':entry.status}</td></tr>)}</tbody></table></div>:<p className="section-description">No payments yet.</p>}</section><Link className="text-button spaced" href="/terms#payment-problems">Payment help & refund requests →</Link></>;
}
