'use client';
import Link from 'next/link';
import { SlotPlans } from './slot-plans';
import { useActionState } from 'react';
import { useRouter } from 'next/navigation';
import { startCheckout } from '@/features/billing/actions';
import { formatDate, formatMoney, type Usage } from '@/lib/domain';
import { capabilities } from '@/features/entitlements/domain';
export interface BillingOrder { id:string;amount_minor:number;currency:string;status:string;created_at:string;period_ends_at:string|null;product?:string;slot_count?:number }
export function Billing({usage,orders=[],enabled=false,returned,demo=false,testMode=false}:{usage:Usage;orders?:BillingOrder[];enabled?:boolean;returned?:string;demo?:boolean;testMode?:boolean}) {
 const [state,action,pending]=useActionState(startCheckout,{});const router=useRouter();const cap=capabilities(usage);
 const temporaryActive=usage.temporary_active ?? cap.slots > 3;
 const freeSlots=3+(usage.bonus_slots??0);
 const slotSummary=usage.permanent ? `Your ${usage.permanent_slots ?? 5} purchased extra slots are permanent.` : temporaryActive && usage.paid_until ? 'Purchased extra slots available through '+formatDate(usage.paid_until)+'. Renew manually whenever you’re ready.' : usage.paid_until ? `Your temporary pack has expired. Your ${freeSlots} free alert slots are still available.` : `Your ${freeSlots} free alert slots are available.`;
 return <><div className="page-heading"><div><div className="eyebrow">A LITTLE MORE ROOM</div><h1>More things can remind you.</h1><p>Keep as many reminders as you need. Choose which ones send alerts.</p></div></div>
 {returned==='return'&&<p className="alert info space-bottom">We’re checking your payment with PayMongo. Access appears after verified confirmation. Refresh status below; please avoid paying again while it is pending.</p>}
 {returned==='cancelled'&&<p className="alert info space-bottom">You returned from checkout. Your access changes only if payment was completed.</p>}
 <section className="panel space-bottom"><h2>Your alert slots</h2><p className="expiry-big">{cap.used} of {cap.slots} slots used</p><p className="section-description">{usage.purchases} saved reminders, including archived · Unlimited reminders</p><p className="hint">{slotSummary}</p>{usage.bonus_slots === 2 && <p className="hint spaced">Includes 2 permanent free slots from your one-time installation and notification reward.</p>}<p className="hint spaced">Documents: {Math.ceil(usage.storage_bytes/1048576)} / {Math.round(cap.storageBytes/1048576)} MB. Alert packs do not add file storage.</p><Link className="text-button spaced" href={(demo?'/demo':'')+'/items?filter=reminders'}>Manage alert coverage →</Link><p className="hint spaced">When a pack expires, your oldest selected reminders keep the available slots; extra selections pause. They resume when capacity returns. You can turn coverage off or move it to another reminder.</p></section>
 <SlotPlans freeSlots={freeSlots} action={demo ? undefined : action} pending={pending} enabled={enabled} permanentSlots={usage.permanent ? usage.permanent_slots ?? 5 : 0} initialSlots={usage.renewal_slots ?? 5} paidUntil={!usage.permanent && usage.paid_until && temporaryActive ? usage.paid_until : null}/>
 {!demo&&!enabled&&<p className="hint spaced">Payments will open after checkout setup is complete.</p>}{testMode&&enabled&&<p className="alert info spaced">Test checkout · no live payment</p>}{state.error&&<p className="alert error spaced" role="alert">{state.error}</p>}
 <p className="hint spaced">Early renewal adds a 30-day term after your remaining prepaid time. Each term uses the slot count purchased for it. Switching to permanent replaces temporary slots immediately, without an automatic prorated refund. No recurring subscription.</p><Link className="text-button" href={(demo?'/demo':'')+'/settings'}>Choose renewal email preferences →</Link>
 <section className="panel spaced"><div className="section-heading"><h2>Payment history</h2><button className="text-button" onClick={()=>router.refresh()}>Refresh status</button></div>{orders.length?<div className="table-scroll"><table className="billing-table"><thead><tr><th>Date</th><th>Reference</th><th>Pack</th><th>Amount</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{formatDate(o.created_at,true)}</td><td><code>{o.id}</code></td><td>{o.product==='legacy_year'?'Annual access':o.slot_count?`${o.slot_count} slots · ${o.product==='slots_permanent'?'Permanent':'30 days'}`:'Alert pack'}</td><td>{formatMoney(o.amount_minor)}</td><td>{o.status==='review'?'Under review':o.status}</td></tr>)}</tbody></table></div>:<p className="section-description">No payments yet.</p>}</section></>;
}
