import Link from 'next/link';
import { ArrowRight, Bell, CalendarDays, ReceiptText, ShieldCheck } from 'lucide-react';
import { type Usage } from '@/lib/domain';
import { dateRows, comingUp, type ItemWithDetails } from '@/features/items/domain';
import { ItemCard, ItemDateRow } from './item-ui';
import { AddItemButton } from './template-picker';
export function Dashboard({ items, usage, name, today, demo = false }: { items: ItemWithDetails[]; usage: Usage; name: string; today: string; demo?: boolean }) {
  const base = demo ? '/demo' : '', rows = dateRows(items), soon = comingUp(rows,today), past = rows.filter(r => r.occurrence.due_on < today), future = rows.filter(r => r.occurrence.due_on >= today).slice(0,5);
  const overdue=usage.overdue??past.length;
  const near = future.filter(r => soon.includes(r)), later = future.filter(r => !soon.includes(r));
  return <><div className="page-heading"><div><div className="eyebrow">A LITTLE LESS TO REMEMBER</div><h1>Everything in its place.</h1><p>Welcome back, {name.split(' ')[0] || 'there'}. A little peace of mind, all together.</p></div><AddItemButton demo={demo} /></div>
    <div className="stat-grid"><Link href={base + '/items'} className="stat-card"><span className="stat-icon violet"><ReceiptText size={21} /></span><div><span>Saved items</span><strong>{usage.purchases}</strong><p>Including archived items</p></div></Link><Link href={base + '/items?filter=reminders'} className="stat-card"><span className="stat-icon green"><Bell size={21} /></span><div><span>Reminder slots</span><strong>{usage.reminders}<small> / {usage.slot_limit??3}</small></strong><p>Items with reminder coverage</p></div></Link><Link href={base + '/items?filter=upcoming'} className="stat-card"><span className="stat-icon amber"><CalendarDays size={21} /></span><div><span>Coming up</span><strong>{usage.upcoming??soon.length}</strong><p>Next 30 days</p></div></Link></div>
    <div className="dashboard-middle"><section className="panel"><div className="section-heading"><h2>A little heads-up</h2><Link href={base + '/items?filter=dates'}>View all <ArrowRight size={15} /></Link></div><p className="section-description">Important dates, with room to plan ahead.</p>{overdue > 0 && <div className="alert error spaced"><Link href={base + '/items?filter=overdue'}>{overdue} overdue or expired {overdue === 1 ? 'date' : 'dates'} — review →</Link></div>}{near.map(row => <ItemDateRow key={row.date.id} row={row} today={today} base={base} />)}{!near.length && <p className="spaced">Nothing due in the next 30 days.</p>}{later.length > 0 && <><h3 className="spaced">Later</h3>{later.map(row => <ItemDateRow key={row.date.id} row={row} today={today} base={base} />)}</>}{!future.length && <Link className="text-button spaced" href={base + '/add'}>Add an important date →</Link>}</section><section className="peace-card"><ShieldCheck size={44} /><h2>Future you will thank you.</h2><p>A receipt. A renewal. The next aircon clean. Give the little things a home.</p><Link href={base + '/add'}>Keep something safe <ArrowRight size={16} /></Link></section></div>
    <section><div className="section-heading recent-heading"><div><h2>Little things, safely kept.</h2><p className="section-description">Your recently added items.</p></div><Link href={base + '/items'}>All items <ArrowRight size={15} /></Link></div><div className="purchase-grid">{(demo?items:[...items].sort((a,b)=>b.created_at.localeCompare(a.created_at))).filter(i => i.state === 'saved' && !i.archived_at).slice(0,6).map(item => <ItemCard key={item.id} item={item} base={base} />)}</div>{!items.length && <p>Add your first item. A name is a good start.</p>}</section><p className="privacy-note"><ShieldCheck size={15} />Your items and files are private to your account.</p></>;
}
