'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, CalendarDays, Sparkles, Pencil } from 'lucide-react';
import { formatDate, formatMoney, parseMoney } from '@/lib/domain';
import { formatTotal } from '@/features/items/insights';
import { plannerMonths, type HouseholdPlanner, type PlannerRow } from '@/features/premium/planner';
import { ItemIdentityIcon } from './reminder-icon';
import styles from './premium.module.css';
function monthName(month:string){return new Intl.DateTimeFormat('en-PH',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(month+'T00:00:00Z'));}
export function HouseholdPlannerView({plan,premium=false,demo=false,month,allSampleRows}:{plan:HouseholdPlanner;premium?:boolean;demo?:boolean;month?:string;allSampleRows?:PlannerRow[]}) {
 const base=demo?'/demo':'',[sampleRows,setSampleRows]=useState(allSampleRows||plan.rows),[editing,setEditing]=useState<string|null>(null),[amount,setAmount]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const months=demo?plannerMonths(sampleRows,plan.today,plan.ends_on):plan.months;
 const rows=demo?sampleRows.filter(row=>!month||row.due_on.slice(0,7)===month.slice(0,7)):plan.rows;
 const highest=months.filter(m=>BigInt(m.total_minor)>0).reduce<typeof months[number]|null>((best,m)=>!best||BigInt(m.total_minor)>BigInt(best.total_minor)?m:best,null);
 const href=(days:number,selected?:string)=>base+'/planner?'+new URLSearchParams({days:String(days),...(selected?{month:selected}:{})});
 const last=rows.at(-1);
 function preview(row:PlannerRow,event:React.FormEvent){event.preventDefault();try{const value=parseMoney(amount);if(value!==null&&value>99999999999)throw new Error();setSampleRows(current=>current.map(entry=>entry.date_id===row.date_id&&entry.due_on===row.due_on?{...entry,amount_minor:value,certainty:value===null?'unset':'estimated',cost_expected:true}:entry));setEditing(null);setError('');setNotice('Sample amount updated. Monthly totals have changed. Nothing is saved.');}catch{setError('Enter a valid amount up to ₱999,999,999.99.');}}
 return <><Link className="back-link" href={base+'/dashboard'}>← Household overview</Link><div className="page-heading"><div><span className="eyebrow">{demo?'PREMIUM SAMPLE':'A LITTLE MORE BREATHING ROOM'}</span><h1>Your household, ahead.</h1><p>Bring your saved bills, maintenance and renewals into one plan.</p></div></div>
 <nav className={styles.horizons} aria-label="Planning period">{[[30,'Next 30 days'],[90,'Next 3 months'],[365,'Year ahead']].map(([days,label])=><Link aria-current={plan.days===days?'page':undefined} className={plan.days===days?styles.active:''} href={href(Number(days))+(!premium&&!demo&&days!==30?'#premium-planner-invitation':'')} key={days}>{label}{days!==30&&<Sparkles size={14} aria-label="Premium"/>}</Link>)}<Link href={base+'/checkup'}>Spending Checkup <Sparkles size={14} aria-label="Premium"/></Link></nav>
 <section className={styles.plannerIntro}><CalendarDays size={25}/><div><h2>{highest?`${monthName(highest.month)} has the highest saved costs in this view.`:'Room to see what’s coming.'}</h2><p>{highest?`${formatTotal(highest.total_minor)} in entered amounts. Review the dates below to prepare at your own pace.`:'Add dates and expected amounts to your household records to build your plan.'}</p><p className="hint">{formatDate(plan.today,true)} to {formatDate(plan.ends_on,true)}. Totals include saved amounts and estimates. Dates without amounts are excluded. This is not a complete household budget.</p></div></section>
 <div className={styles.months} aria-label="Monthly household costs">{months.map(m=><Link key={m.month} className={styles.month+(month===m.month?' '+styles.selected:'')} href={href(plan.days,m.month)} aria-current={month===m.month?'page':undefined}><span>{monthName(m.month)}</span><strong>{formatTotal(m.total_minor)}</strong><small>{m.date_count} {m.date_count===1?'date':'dates'} · entered costs</small>{m.estimated_count>0&&<small>{m.estimated_count} {m.estimated_count===1?'estimate':'estimates'}</small>}{m.unset_count>0&&<small>{m.unset_count} {m.unset_count===1?'payment needs':'payments need'} an amount</small>}</Link>)}</div>
 {(!premium&&!demo)&&<section id="premium-planner-invitation" className={styles.upgrade}><Sparkles size={25}/><div><h2>Give the months ahead a little more breathing room.</h2><p>Plan beyond 30 days, explore monthly costs, and prepare for upcoming maintenance and renewals with Keeply Premium.</p><p><strong>Install Keeply for 30 days of full Premium.</strong> No card. No payment details. No automatic charges.</p><div className="hero-actions spaced"><Link className="button primary" href="/settings/alerts">Show me how to install</Link><Link className="button secondary" href="/demo/planner?days=365">Explore a sample account</Link><Link className="text-button" href="/settings/billing">See Premium plans</Link></div></div></section>}
 <div className="section-heading spaced"><h2>{month?monthName(month):'Dates in your plan'}</h2>{month&&<Link href={href(plan.days)} className="text-button">Show all months</Link>}</div><p className="hint">Projected dates follow your saved repeating schedules. Open a record to update its date, amount or schedule. Completion-based services appear only when a next date is saved.</p>
 <p role="status" className="hint spaced">{notice}</p><ol className={styles.rows}>{rows.map(row=>{const key=row.date_id+':'+row.due_on;return <li key={key} className={styles.row}><div className={styles.rowIdentity}><ItemIdentityIcon item={row.identity}/><div><Link href={base+'/items/'+row.item_id+'#date-'+row.date_id}><strong>{row.product_name}</strong></Link><p>{row.label} · {formatDate(row.due_on,true)}</p>{row.projected&&<small>Projected from saved schedule</small>}</div></div><div className={styles.rowAmount}><strong>{row.amount_minor==null?row.cost_expected?'Amount to add':'Date to prepare for':formatMoney(row.amount_minor)}</strong>{row.amount_minor!=null&&<small>{row.certainty==='estimated'?'Estimated cost':'Expected cost'}</small>}{demo&&row.cost_expected&&editing!==key&&<button className="text-button" type="button" onClick={()=>{setEditing(key);setAmount(row.amount_minor==null?'':String(row.amount_minor/100));setError('');}}><Pencil size={14}/>Change amount</button>}{!demo&&<Link className="text-button" href={'/items/'+row.item_id+'#date-'+row.date_id}>Review record <ArrowRight size={14}/></Link>}</div>{demo&&editing===key&&<form className={styles.editor} onSubmit={event=>preview(row,event)}><label>Sample expected amount (₱)<input autoFocus inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)}/></label>{error&&<p role="alert" className="alert error">{error}</p>}<div className="hero-actions"><button type="submit" className="button primary">Update sample plan</button><button type="button" className="button secondary" onClick={()=>setEditing(null)}>Cancel</button></div></form>}</li>;})}</ol>
 {!rows.length&&<p className="panel spaced">No dates saved in this part of your plan. You can add obligations whenever you’re ready.</p>}
 {!demo&&plan.has_more&&last&&<Link className="button secondary spaced" href={href(plan.days,month)+'&'+new URLSearchParams({before:last.due_on,id:last.date_id})}>More dates</Link>}
 {demo&&<section className={styles.upgrade}><GiftCopy/></section>}</>;
}
function GiftCopy(){return <div><span className="eyebrow">MAKE ROOM FOR YOUR OWN HOUSEHOLD</span><h2>Enjoy this view with your own records.</h2><p>Install Keeply and get 30 days of full Premium. No card, payment details or automatic charges.</p><Link href="/add" className="button primary spaced">Start my household account <ArrowRight size={16}/></Link></div>;}
