'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, CalendarDays, Sparkles, Pencil } from 'lucide-react';
import { formatDate, formatMoney, parseMoney } from '@/lib/domain';
import { formatTotal } from '@/features/items/insights';
import {premiumExpiry,premiumExpiryHeading} from '@/features/premium/discovery';
import type {Usage} from '@/lib/domain';
import { type HouseholdPlanner, type PlannerRow } from '@/features/premium/planner';
import { sampleOutlook, isOutlookMonth, type HouseholdOutlook } from '@/features/premium/outlook';
import { HouseholdOutlookSummary, MonthCoverage, OutlookAmount, OutlookContributors, outlookMonthName as monthName } from './household-outlook-summary';
import outlookStyles from './household-outlook.module.css';
import { ItemIdentityIcon } from './reminder-icon';
import styles from './premium.module.css';
export function HouseholdPlannerView({plan,premium=false,demo=false,month,allSampleRows,before,beforeId,usage,requestedDays}:{plan:HouseholdPlanner|HouseholdOutlook;premium?:boolean;demo?:boolean;month?:string;allSampleRows?:PlannerRow[];before?:string;beforeId?:string;usage?:Usage;requestedDays?:number}) {
 const base=demo?'/demo':'',[sampleRows,setSampleRows]=useState(allSampleRows||plan.rows),[editing,setEditing]=useState<string|null>(null),[amount,setAmount]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const outlook=demo?sampleOutlook(sampleRows,plan.today,plan.days,month,before,beforeId):'costs' in plan?plan:undefined;
 const months=outlook?.months??plan.months;
 const selectedMonth=outlook?.month??(months.some(entry=>entry.month===month)?month:undefined);
 const rows=outlook?.rows??plan.rows,selected=outlook?.months.find(entry=>entry.month===selectedMonth);
 const href=(days:number,selected?:string)=>base+'/planner?'+new URLSearchParams({days:String(days),...(selected?{month:selected}:{})});
 const last=rows.at(-1);
 function preview(row:PlannerRow,event:React.FormEvent){event.preventDefault();try{const value=parseMoney(amount);if(value!==null&&value>99999999999)throw new Error();setSampleRows(current=>current.map(entry=>entry.date_id===row.date_id&&entry.due_on===row.due_on?{...entry,amount_minor:value,certainty:value===null?'unset':'estimated',cost_expected:true}:entry));setEditing(null);setError('');setNotice('Sample amount updated. Monthly totals have changed. Nothing is saved.');}catch{setError('Enter a valid amount up to ₱999,999,999.99.');}}
 return <div data-premium-surface="outlook"><Link className="back-link" href={base+'/dashboard'}>← Household overview</Link><div className="page-heading"><div><span className="eyebrow">{demo?'PREMIUM SAMPLE':'A LITTLE MORE BREATHING ROOM'}</span><h1>Your Household Outlook</h1><p>Plan for upcoming bills, maintenance, and renewals.</p><p className="hint">{formatDate(plan.today,true)} to {formatDate(plan.ends_on,true)}. Dates follow your saved schedules.</p></div></div>
 <nav className={styles.horizons} aria-label="Planning period">{[[30,'Next 30 days'],[90,'Next 3 months'],[365,'Year ahead']].map(([days,label])=><Link aria-current={plan.days===days?'page':undefined} className={plan.days===days?styles.active:''} data-premium-event={days===30?'calendar_30d_used':'extended_planner_requested'} data-premium-horizon={days} href={href(Number(days))+(!premium&&!demo&&days!==30?'#premium-planner-invitation':'')} key={days}>{label}{days!==30&&<Sparkles size={14} aria-label="Premium"/>}</Link>)}<Link href={base+'/checkup'}>Spending Checkup <Sparkles size={14} aria-label="Premium"/></Link></nav>
 {outlook?<HouseholdOutlookSummary plan={outlook} base={base}/>:<section className={styles.plannerIntro}><CalendarDays size={25} aria-hidden="true"/><div><h2>Your next 30 days, together.</h2><p>Review your saved household dates and expected costs. Dates without amounts stay in your plan.</p><p className="hint">Amounts include estimates. This is not a complete household budget.</p></div></section>}
 <nav className={styles.months} aria-label="Monthly household costs">{months.map(m=><Link key={m.month} className={styles.month+(selectedMonth===m.month?' '+styles.selected:'')} data-premium-event="outlook_month_inspected" data-premium-insight="month" href={href(plan.days,m.month)+'#outlook-dates'} onClick={()=>setEditing(null)} aria-current={selectedMonth===m.month?'page':undefined}><span>{monthName(m.month)}</span><strong>{isOutlookMonth(m)?<OutlookAmount month={m}/>:m.date_count===0?'No dates added':BigInt(m.total_minor)===0n&&m.unset_count>0?'Amounts to add':formatTotal(m.total_minor)}</strong><small>{m.date_count} household {m.date_count===1?'date':'dates'}</small>{isOutlookMonth(m)&&<MonthCoverage month={m}/>}{isOutlookMonth(m)&&BigInt(m.costs.estimated_minor)>0n?<small>{formatTotal(m.costs.estimated_minor)} estimated</small>:m.estimated_count>0&&<small>{m.estimated_count} {m.estimated_count===1?'estimate':'estimates'}</small>}{m.unset_count>0&&<small>{m.unset_count} {m.unset_count===1?'expense needs':'expenses need'} an amount</small>}</Link>)}</nav>
 {selected&&<section className={outlookStyles.selectedMonth} aria-labelledby="outlook-selected-heading"><h2 id="outlook-selected-heading">{monthName(selected.month)}</h2><MonthCoverage month={selected}/><p className={outlookStyles.total}><OutlookAmount month={selected}/></p>{selected.costs.unset_count>0&&<p className="hint">{selected.costs.unset_count} {selected.costs.unset_count===1?'amount is':'amounts are'} still unknown. Recorded costs can change when you add them.</p>}{selected.contributors.length>0&&<OutlookContributors month={selected} base={base}/>}</section>}
 {(!premium&&!demo)&&<section id="premium-planner-invitation" className={styles.upgrade} data-premium-preview="" data-premium-expired={usage&&premiumExpiry(usage)?'':undefined}><Sparkles size={25}/><div><h2>{usage&&premiumExpiry(usage)?premiumExpiryHeading(usage):requestedDays===365?'See a year of household obligations':requestedDays===90?'See the next three months together':'Understand the months ahead'}</h2><p>Your Free plan below covers the next 30 days. Premium adds monthly comparisons and planning up to a year ahead, using your saved dates and expected costs.</p>{usage&&premiumExpiry(usage)&&<p>Your records, history, alerts and amount editing remain available. Unlock Premium again whenever it helps.</p>}<p>₱59 for 30 days · ₱499 for one year · No automatic renewal</p>{!usage?.installation_premium_claimed&&<p>Install Keeply and open it while signed in for a one-time 30-day Premium gift. No card or payment details.</p>}<div className="hero-actions spaced"><Link className="button primary" href="/demo/planner?days=365" data-premium-event="premium_sample_opened">Explore a sample account</Link><Link className="button secondary" href="/settings/billing">See Premium plans</Link>{!usage?.installation_premium_claimed&&<Link className="text-button" href="/settings/alerts" data-premium-event="installation_guide_opened">Show me how to install</Link>}</div></div></section>}
 <div className="section-heading spaced"><h2 className={outlookStyles.datesHeading} tabIndex={-1} id="outlook-dates">{selectedMonth?'Dates in '+monthName(selectedMonth):'Dates in your plan'}</h2>{selectedMonth&&<Link href={href(plan.days)} className="text-button">Show all months</Link>}</div><p className="hint">{outlook?outlook.filtered_total:plan.total} household dates in this selection. Projected dates follow your saved repeating schedules. Open a record to update its date, amount or schedule. Completion-based services appear only when a next date is saved.</p>
 <p role="status" className="hint spaced">{notice}</p><ol className={styles.rows}>{rows.map(row=>{const key=row.date_id+':'+row.due_on;return <li key={key} className={styles.row}><div className={styles.rowIdentity}><ItemIdentityIcon item={row.identity}/><div><Link data-premium-event="insight_source_opened" data-premium-insight="contributors" href={base+'/items/'+row.item_id+'#date-'+row.date_id}><strong>{row.product_name}</strong></Link><p>{row.label} · {formatDate(row.due_on,true)}</p>{row.projected&&<small>Projected from saved schedule</small>}</div></div><div className={styles.rowAmount}><strong>{row.amount_minor==null?row.cost_expected?'Amount to add':'Date to prepare for':formatMoney(row.amount_minor)}</strong>{row.amount_minor!=null&&<small>{row.certainty==='estimated'?'Estimated amount':row.certainty==='confirmed'?'Confirmed amount':'Expected amount'}</small>}{demo&&row.cost_expected&&editing!==key&&<button className="text-button" type="button" onClick={()=>{setEditing(key);setAmount(row.amount_minor==null?'':String(row.amount_minor/100));setError('');}}><Pencil size={14}/>Change amount</button>}{!demo&&<Link className="text-button" href={'/items/'+row.item_id+'#date-'+row.date_id}>Review record <ArrowRight size={14}/></Link>}</div>{demo&&editing===key&&<form className={styles.editor} onSubmit={event=>preview(row,event)}><label>Sample expected amount (₱)<input autoFocus inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)}/></label>{error&&<p role="alert" className="alert error">{error}</p>}<div className="hero-actions"><button type="submit" className="button primary">Update sample plan</button><button type="button" className="button secondary" onClick={()=>setEditing(null)}>Cancel</button></div></form>}</li>;})}</ol>
 {!rows.length&&<p className={outlookStyles.empty}>{outlook&&outlook.filtered_total>0?'You’ve reached the end of this selection.':'No dates saved in this part of your plan. Add obligations whenever you’re ready. Empty months do not mean there will be no household expenses.'}</p>}
 {before&&<Link className="button secondary spaced" href={href(plan.days,selectedMonth||undefined)+'#outlook-dates'}>First page</Link>}{(outlook?.has_more??plan.has_more)&&last&&<Link className="button secondary spaced" href={href(plan.days,selectedMonth||undefined)+'&'+new URLSearchParams({before:last.due_on,id:last.date_id})+'#outlook-dates'}>More dates</Link>}
 {demo&&<section className={styles.upgrade}><GiftCopy/></section>}</div>;
}
function GiftCopy(){return <div><span className="eyebrow">MAKE ROOM FOR YOUR OWN HOUSEHOLD</span><h2>Enjoy this view with your own records.</h2><p>Install Keeply and get 30 days of full Premium. No card, payment details or automatic charges.</p><Link href="/add" className="button primary spaced">Start my household account <ArrowRight size={16}/></Link></div>;}
