'use client';
import Link from 'next/link';
import { useState } from 'react';
import { CalendarDays, Lightbulb } from 'lucide-react';
import { formatDate } from '@/lib/domain';
import { formatTotal } from '@/features/items/insights';
import { outlookDifference, outlookHighest, partialMonth, type HouseholdOutlook, type OutlookMonth } from '@/features/premium/outlook';
import styles from './household-outlook.module.css';

export function outlookMonthName(month:string) {
 return new Intl.DateTimeFormat('en-PH',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(month+'T00:00:00Z'));
}
export function MonthCoverage({month}:{month:OutlookMonth}) {
 return <small>{formatDate(month.starts_on,true)} to {formatDate(month.ends_on,true)}{partialMonth(month)?' · Partial month':''}</small>;
}
export function OutlookAmount({month}:{month:OutlookMonth}) {
 return <>{month.costs.known_count?formatTotal(month.total_minor):month.costs.total?'Amounts to add':month.date_count?'No costs added':'No dates added'}</>;
}
export function OutlookContributors({month,base}:{month:OutlookMonth;base:string}) {
 return <><h3>Largest recorded costs</h3><p className="hint">Up to three expenses, across every date in this month.</p><ol className={styles.contributors}>{month.contributors.map(row=><li key={row.date_id}><div><Link href={base+'/items/'+row.item_id+'#date-'+row.date_id}>{row.product_name}</Link><small>{row.label} · {row.costs.total} scheduled {row.costs.total===1?'date':'dates'}</small>{row.costs.unset_count>0&&<small>{row.costs.unset_count} {row.costs.unset_count===1?'amount':'amounts'} to add</small>}</div><div><strong>{formatTotal(row.costs.total_minor)}</strong>{BigInt(row.costs.estimated_minor)>0n&&<small>{formatTotal(row.costs.estimated_minor)} estimated</small>}</div></li>)}</ol></>;
}
export function HouseholdOutlookSummary({plan,base}:{plan:HouseholdOutlook;base:string}) {
 const highest=outlookHighest(plan),months=plan.months;
 const [firstId,setFirst]=useState(months[0].month),[secondId,setSecond]=useState(months[1]?.month??months[0].month);
 const first=months.find(month=>month.month===firstId)??months[0],second=months.find(month=>month.month===secondId)??months[0];
 const difference=outlookDifference(first,second);
 const href=(month:string)=>base+'/planner?'+new URLSearchParams({days:String(plan.days),month})+'#outlook-dates';
 return <><div className={styles.overview}>
  <section className={styles.card} aria-labelledby="outlook-total-heading"><h2 id="outlook-total-heading">Recorded upcoming costs</h2><p className={styles.total}>{plan.costs.known_count?formatTotal(plan.total_minor):plan.costs.total?'Amounts not yet known':plan.total?'No costs added':'No dates added'}</p><p>{plan.costs.total} upcoming {plan.costs.total===1?'expense':'expenses'} across {plan.total} household {plan.total===1?'date':'dates'}.</p>{BigInt(plan.costs.estimated_minor)>0n&&<p>{formatTotal(plan.costs.estimated_minor)} of this total is estimated.</p>}{plan.costs.unset_count>0&&<p>{plan.costs.unset_count} {plan.costs.unset_count===1?'expense needs':'expenses need'} an amount. Missing amounts are excluded from the total.</p>}<p className="hint">Based on expenses you’ve added. Paid, completed, and overdue dates are excluded. Saved costs do not prove payment.</p><Link href="#outlook-dates" className="text-button">Review dates and amounts</Link></section>
  <section className={styles.card} aria-labelledby="outlook-highest-heading"><CalendarDays size={24} aria-hidden="true"/><h2 id="outlook-highest-heading">{highest?highest.only_month?'Your recorded costs fall in one month':highest.ties>1?'Months sharing the highest total':'Highest recorded monthly total':'Build your household outlook'}</h2>{highest?<><p className={styles.monthName}>{outlookMonthName(highest.month.month)}</p><p className={styles.total}>{formatTotal(highest.month.total_minor)}</p><MonthCoverage month={highest.month}/>{highest.ties>1&&<p>{highest.ties} months share this recorded total. The earliest is shown.</p>}{plan.costs.unset_count>0&&<p>Missing amounts can change this comparison.</p>}<p className="hint">Calendar months are compared by recorded totals. The first and last may cover fewer days.</p><p className="hint">Largest recorded costs: {highest.month.contributors.slice(0,2).map((row,index)=><span key={row.date_id}>{index>0?'; ':''}<Link href={base+'/items/'+row.item_id+'#date-'+row.date_id}>{row.product_name}</Link> ({formatTotal(row.costs.total_minor)})</span>)}.</p><Link className="text-button" href={href(highest.month.month)}>Inspect this month</Link></>:<><p>{plan.costs.total===0?'Add expected household costs to start planning ahead.':plan.positive_source_count<2?'Add amounts for more than one household expense to make comparisons useful.':'Add more expected costs when you know them.'}</p><p className="hint">Dates without costs remain in your plan. Empty months do not mean your household will have no expenses.</p></>}</section>
 </div>
 {highest&&months.length>1&&<section className={styles.comparison} aria-labelledby="outlook-comparison-heading"><h2 id="outlook-comparison-heading"><Lightbulb size={21} aria-hidden="true"/>Compare recorded monthly costs</h2><div className={styles.compareChoices}><div><label htmlFor="outlook-first-month">First month</label><select id="outlook-first-month" value={first.month} onChange={event=>setFirst(event.target.value)}>{months.map(month=><option key={month.month} value={month.month}>{outlookMonthName(month.month)}</option>)}</select></div><div><label htmlFor="outlook-second-month">Second month</label><select id="outlook-second-month" value={second.month} onChange={event=>setSecond(event.target.value)}>{months.map(month=><option key={month.month} value={month.month}>{outlookMonthName(month.month)}</option>)}</select></div></div><div className={styles.compareFigures}>{[first,second].map((month,index)=><div key={index}><h3>{outlookMonthName(month.month)}</h3><strong><OutlookAmount month={month}/></strong><MonthCoverage month={month}/>{BigInt(month.costs.estimated_minor)>0n&&<small>{formatTotal(month.costs.estimated_minor)} estimated</small>}{month.costs.unset_count>0&&<small>{month.costs.unset_count} {month.costs.unset_count===1?'amount':'amounts'} to add</small>}<Link href={href(month.month)}>Inspect contributing dates</Link></div>)}</div><p role="status" className={styles.difference}>{first.month===second.month?'Choose two different months.':difference===null?'Add expected amounts in both months before comparing recorded costs.':difference===0n?'These periods have the same recorded costs.':`${outlookMonthName(second.month)} has ${formatTotal((difference<0n?-difference:difference).toString())} ${difference<0n?'less':'more'} in recorded costs than ${outlookMonthName(first.month)}.`}</p><p className="hint">This compares the dates shown, including estimates. It does not measure changes since a previous review.{partialMonth(first)||partialMonth(second)?' One or both periods cover only part of a month.':''}{first.costs.unset_count+second.costs.unset_count>0?' Missing amounts can change the difference.':''}</p></section>}
 </>;
}
