'use client';
import Image from 'next/image';
import { useRef, useState } from 'react';
import { Smartphone, Monitor, ArrowRight, X, Gift } from 'lucide-react';
import { installSteps, type InstallDevice } from '@/lib/install-guide';
import styles from './install-setup.module.css';
export function InstallSetup({accountId,claimed=false,dashboard=false}:{publicKey:string|null;accountId:string;claimed?:boolean;dashboard?:boolean}) {
 const dialog=useRef<HTMLDialogElement>(null),heading=useRef<HTMLHeadingElement>(null);
 const [device,setDevice]=useState<InstallDevice|null>(null),[step,setStep]=useState(0),[dismissed,setDismissed]=useState(false);
 const steps=device?installSteps[device]:[],current=steps[step];
 function open(){setDevice(null);setStep(0);dialog.current?.showModal();}
 function next(value:number){setStep(value);requestAnimationFrame(()=>heading.current?.focus());}
 return <>{dashboard&&(dismissed||claimed)?<div className={styles.returnLink}><button type="button" className="text-button" onClick={open}>{claimed?'Add Keeply to another device':'Install Keeply & enjoy 30 days of Premium'} <ArrowRight size={15}/></button></div>:<section className={styles.card} aria-label="Install Keeply"><span className={styles.icon}><Gift size={27}/></span><div className={styles.copy}><span className="eyebrow">A LITTLE GIFT FOR YOUR HOUSEHOLD</span><h2>{claimed?'Keeply goes with you.':'Install Keeply. Enjoy 30 days of full Premium.'}</h2><p>{claimed?'Keep your household a tap away on another device. Your account and Premium access go with you.':'No card. No payment details. No automatic charges. Install and open Keeply while signed in, and your gift activates automatically.'}</p>{!claimed&&<p>One gift per account. Notifications are optional.</p>}</div><button type="button" className="button primary" onClick={open}>Show me how <ArrowRight size={16}/></button>{dashboard&&<button type="button" className={'icon-button '+styles.dismiss} aria-label="Dismiss installation card" onClick={()=>setDismissed(true)}><X size={18}/></button>}</section>}
 <dialog ref={dialog} className={styles.dialog} aria-labelledby={'install-title-'+accountId} onClose={()=>{setDevice(null);setStep(0);}}><div className={styles.header}><span className="eyebrow">{device?`STEP ${step+1} OF ${steps.length}`:'YOUR PREMIUM GIFT STARTS HERE'}</span><button type="button" className="icon-button" aria-label="Close installation guide" onClick={()=>dialog.current?.close()}><X size={21}/></button></div>
 <h2 id={'install-title-'+accountId} ref={heading} tabIndex={-1}>{current?current.title:'Where would you like to add Keeply?'}</h2>
 {!device?<><p className={styles.description}>Choose your device. Install Keeply and open its icon while signed in. Your 30 days of full Premium activate automatically, without a card or any payment details.</p><div className={styles.choices}>{([['ios','iPhone or iPad','Guide with screenshots'],['android','Android','Step-by-step guide'],['computer','Computer','Windows, Mac, Chromebook or Linux']] as const).map(([key,label,hint])=><button type="button" className={styles.choice} key={key} onClick={()=>{setDevice(key);next(0);}}>{key==='computer'?<Monitor size={24}/>:<Smartphone size={24}/>}<span><strong>{label}</strong><small>{hint}</small></span><ArrowRight size={18}/></button>)}</div><p className="hint">One gift per account. No notification permission required. No automatic charge when the gift ends.</p></>:<><progress className={styles.progress} value={step+1} max={steps.length} aria-label="Installation progress"/><p className={styles.description}>{current.text}</p>{current.image&&<figure className={styles.figure}><a href={current.image} target="_blank" rel="noopener noreferrer" aria-label="Open screenshot at full size"><Image src={current.image} alt={current.alt||current.title} width={600} height={1100} sizes="(max-width:600px) 85vw, 420px" className={styles.screenshot}/></a><figcaption>Look for the control circled in red. Tap the image to enlarge it.</figcaption></figure>}{current.hint&&<p className={'alert info '+styles.hint}>{current.hint}</p>}{step===steps.length-1&&<p className="alert success">Your gift activates when you open the installed app while signed in. No card or payment details needed.</p>}</>}
 <div className={styles.footer}>{device?<><button type="button" className="button secondary" onClick={()=>step?next(step-1):setDevice(null)}>Back</button>{step<steps.length-1?<button type="button" className="button primary" onClick={()=>next(step+1)}>Next <ArrowRight size={16}/></button>:<button type="button" className="button primary" onClick={()=>dialog.current?.close()}>Got it</button>}</>:<button type="button" className="text-button" onClick={()=>dialog.current?.close()}>Maybe later</button>}</div></dialog></>;
}
