'use client';
import { reminderCategories } from '@/features/templates/categories';
import Link from 'next/link';
import type { ItemQuery } from '@/features/items/queries';
import { useState } from 'react';
import { readinessChecks, readinessComplete, sampleSearchMatches } from '@/features/items/insights';
import { dateRows, comingUp, itemsForCategory, type ItemWithDetails } from '@/features/items/domain';
import { ItemCard, ItemDateRow } from './item-ui';
import { sampleUnconfirmed } from '@/lib/demo';
import { ReminderReviewRows } from './occurrence-review-list';
import { AddItemButton } from './template-picker';
import { ListFilterFields } from './list-filter-fields';
export function ItemList({ items, today, initialFilter = 'all', demo = false, serverQuery }: { items: ItemWithDetails[]; today: string; initialFilter?: string; demo?: boolean; serverQuery?: ItemQuery }) {
  const [query,setQuery] = useState(serverQuery?.q || ''), [type,setType] = useState(serverQuery?.template || 'all'), [filter,setFilter] = useState(initialFilter);
  if(!demo) return <PagedItems items={items} today={today} query={serverQuery||{filter:initialFilter}}/>;
  const base = demo ? '/demo' : '';
  const matched = itemsForCategory(items, type.startsWith('category:') ? type.slice(9) : 'all').filter(i => sampleSearchMatches(i,query));
  const rows = dateRows(matched);
  const shownDates = filter === 'upcoming' ? comingUp(rows,today) : filter === 'overdue' ? rows.filter(r => r.occurrence.due_on < today) : filter === 'reminders' ? rows.filter(r => r.item.coverage==='covered' && r.date.reminders_enabled && r.occurrence.due_on >= today) : rows;
  const past = filter === 'overdue' ? sampleUnconfirmed(matched) : {total:0,rows:[],has_more:false};
  const dateView = ['upcoming','overdue','dates'].includes(filter);
  const shown = matched.filter(i => filter === 'archived' ? Boolean(i.archived_at) : filter === 'drafts' ? i.state === 'draft' : i.state === 'saved' && !i.archived_at && (filter!=='reminders'||i.coverage==='covered') && (filter!=='uncovered'||i.coverage!=='covered') && (filter!=='incomplete'||!readinessComplete(readinessChecks(i))));
  return <><div className="page-heading"><div><h1>{filter === 'all' ? 'Household items' : filter === 'archived' ? 'Archived items' : filter === 'drafts' ? 'Unfinished items' : 'Household items'}</h1><p>Find an item, its supporting details, or the date you need.</p></div><AddItemButton demo={demo} /></div><div className="filter-panel compact-list-filters"><label className="filter-search"><span className="filter-search-label">Search</span><input type="search" placeholder="Name, notes, history, date or file" value={query} onChange={e => setQuery(e.target.value)} /></label><ListFilterFields activeCount={Number(type !== 'all') + Number(filter !== 'all')}><label>Category<select aria-label="Category" value={type} onChange={e => setType(e.target.value)}><option value="all">All categories</option>{reminderCategories.map(group => <option key={group.key} value={'category:' + group.key}>{group.label}</option>)}</select></label><label>Show<select aria-label="Show" value={filter} onChange={e => setFilter(e.target.value)}>{[['all','Household items'],['incomplete','Incomplete records'],['upcoming','Next 30 days'],['dates','All important dates'],['overdue','Overdue / expired'],['reminders','With alert coverage'],['uncovered','Without alert coverage'],['archived','Archived'],['drafts','Unfinished']].map(([k,l]) => <option key={k} value={k}>{l}</option>)}</select></label></ListFilterFields></div><p className="section-description space-bottom">{dateView ? (shownDates.length + past.total) + ' reminders' : shown.length + ' items'} · Little things, safely kept.</p>{dateView ? <section className="panel">{filter === 'overdue' ? <ReminderReviewRows rows={shownDates} summary={past} base={base} /> : shownDates.map(row => <ItemDateRow key={row.date.id} row={row} today={today} base={base} />)}{!shownDates.length && (filter !== 'overdue' || !past.total) && <p>No dates match this view.</p>}</section> : <div className="purchase-grid">{shown.map(item => <ItemCard key={item.id} item={item} base={base} />)}{!shown.length && <p>No items here yet. Add something you want to organise.</p>}</div>}</>;
}

function PagedItems({items,today,query}:{items:ItemWithDetails[];today:string;query:ItemQuery}) {
 const filter=query.filter||'all'; const visible=itemsForCategory(items,query.template?.startsWith('category:') ? query.template.slice(9) : 'all'); const rows=dateRows(visible);const dates=['dates','upcoming','overdue'].includes(filter);
 const shown=filter==='upcoming'?comingUp(rows,today):filter==='overdue'?rows.filter(r=>r.occurrence.due_on<today):rows;
 const next=new URLSearchParams({filter,q:query.q||'',template:query.template||'all'});const last=items.at(-1);if(last){next.set('cursor',last.created_at);next.set('cursorId',last.id);}
 return <><div className="page-heading"><div><h1>{filter === 'all' ? 'Household items' : filter === 'archived' ? 'Archived items' : filter === 'drafts' ? 'Unfinished items' : 'Household items'}</h1><p>Your household items, important dates and supporting details.</p></div><AddItemButton/></div>
 <form action="/items" className="filter-panel compact-list-filters"><label className="filter-search"><span className="filter-search-label">Search</span><input name="q" type="search" maxLength={160} defaultValue={query.q} placeholder="Name, notes, history, date or file"/></label><ListFilterFields activeCount={Number(Boolean(query.template && query.template !== 'all')) + Number(filter !== 'all')}><label>Category<select aria-label="Category" name="template" defaultValue={query.template||'all'}><option value="all">All categories</option>{reminderCategories.map(group => <option key={group.key} value={'category:' + group.key}>{group.label}</option>)}</select></label><label>Show<select aria-label="Show" name="filter" defaultValue={filter}>{[['all','Household items'],['incomplete','Incomplete records'],['reminders','With alert coverage'],['uncovered','Without alert coverage'],['upcoming','Next 30 days'],['overdue','Overdue / expired'],['dates','All dates'],['archived','Archived'],['drafts','Unfinished']].map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label></ListFilterFields><button className="button secondary filter-submit">Find items</button></form>
 <p className="hint space-bottom">Showing {items.length} items on this page. Search includes saved notes, history, dates and ready file names.</p>{dates?<section className="panel">{shown.map(r=><ItemDateRow key={r.date.id} row={r} today={today}/>)}{!shown.length&&<p>No dates here.</p>}</section>:<div className="purchase-grid">{visible.map(i=><ItemCard key={i.id} item={i}/>)}{!items.length&&<p>No reminders match this view.</p>}</div>}
 <div className="form-actions">{query.cursor&&<Link className="button secondary" href={'/items?'+new URLSearchParams({filter,q:query.q||'',template:query.template||'all'})}>First page</Link>}{items.length===25&&<Link className="button secondary" href={'/items?'+next}>Next page →</Link>}</div></>;
}
