'use client';
import Link from 'next/link';
import { useRef, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { recurrenceFrequencies, nextRecurringDate } from '@/features/items/recurrence';
import { addMonths, formatDate, formatMoney } from '@/lib/domain';
import { templates, getReminderPreset } from '@/features/templates';
import { currentOccurrence, dateStatus, type ItemWithDetails, type DateWithDetails } from '@/features/items/domain';
import { dateHistory, saveDate, completeDate, archiveItem, deleteItem } from '@/features/items/actions';
import { DateFields, initialDate, type DateInput } from './date-fields';
import { CoverageControl } from './reminder-management';
import { ReminderIcon, DateIcon } from './reminder-icon';
import { ItemDocuments } from './item-documents';
import { nextAlertSummary, timingLabel } from '@/features/items/alert-schedule';
function DateEditor({ item, date, demo, onClose }: { item: ItemWithDetails; date?: DateWithDetails; demo: boolean; onClose: () => void }) {
  const router=useRouter(), id=useRef(date?.id || '');
  const [value,setValue]=useState<DateInput>(date ? { kind:date.kind,label:date.label,due_on:currentOccurrence(date)?.due_on || '',reminders_enabled:date.reminders_enabled,offsets:date.offsets,interval_months:date.interval_months, recurrence_months:date.recurrence_months, recurrence_ends_on:date.recurrence_ends_on, recurrence_anchor:date.recurrence_anchor, payment_amount_minor:date.payment_amount_minor } : { ...initialDate(item.template_key), ...(getReminderPreset(item.template_key, item.reminder_preset || undefined) ? { label: getReminderPreset(item.template_key, item.reminder_preset || undefined)!.dateLabel } : {}) });
  const [error,setError]=useState(''), [busy,setBusy]=useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); if(demo){ setError('This preview does not store changes. Sign in to save your dates.'); return; } setBusy(true);setError(''); try { id.current ||= crypto.randomUUID(); const r=await saveDate(id.current,item.id,date?.revision || 0,value);if(r.error) throw new Error(r.error);onClose();router.refresh(); }catch(e){setError(e instanceof Error ? e.message : 'Unable to save.');}finally{setBusy(false);} }
  return <form onSubmit={submit} className="panel spaced"><fieldset disabled={busy}><h3>{date ? 'Edit date & alerts' : 'Add an important date'}</h3><DateFields preset={item.reminder_preset} template={item.template_key} value={value} onChange={setValue}/>{error && <p className="alert error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">{busy ? 'Saving…' : 'Save date'}</button></div></fieldset></form>;
}
function DateCard({ item, date, today, demo }: { item:ItemWithDetails;date:DateWithDetails;today:string;demo:boolean }) {
  const intent = useSearchParams();
  const selected = intent.get('date') === date.id;
  const router=useRouter(), current=currentOccurrence(date), [edit,setEdit]=useState(selected && intent.get('action') === 'edit'), [done,setDone]=useState(selected && intent.get('action') === 'complete' && date.kind !== 'warranty' && Boolean(current) && intent.get('due') === current?.due_on), [completed,setCompleted]=useState(today), [next,setNext]=useState(''), [error,setError]=useState(''), [busy,setBusy]=useState(false);
  const [history,setHistory]=useState(date.occurrences),[hasOlder,setHasOlder]=useState(date.occurrences.length===20);
  async function older(){setBusy(true);try{const rows=await dateHistory(date.id,Math.min(...history.map(o=>o.cycle)));setHistory(h=>[...h,...rows]);setHasOlder(rows.length===20);}catch{setError('Unable to load older history.');}finally{setBusy(false);}}
  async function complete(e:React.FormEvent){e.preventDefault();if(demo){setError('This preview does not store changes.');return;}setBusy(true);setError('');try{const r=await completeDate(date.id,date.revision,completed,next);if(r.error)throw new Error(r.error);setDone(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to complete.');}finally{setBusy(false);}}
  const alert = nextAlertSummary(item, date, today);
  return <section className="panel spaced" id={'date-'+date.id}><div className="section-heading"><h2 className="date-title"><DateIcon kind={date.kind} label={date.label} preset={item.reminder_preset} size={18}/>{date.label}</h2><button className="text-button" onClick={()=>setEdit(!edit)}>{edit?'Close editor':'Edit date & schedule'}</button></div>
    <div className="reminder-date-summary">
      <div><span className="hint">Due date</span><p className="expiry-big">{current ? formatDate(current.due_on) : date.recurrence_months ? 'Schedule ended' : 'Completed'}</p>{current && <p className={'date-countdown' + (current.due_on <= today ? ' date-countdown-urgent' : '')}>{dateStatus({ item, date, occurrence: current }, today)}</p>}</div>
      <div><span className="hint">{alert.label}</span><p className="next-alert-value">{alert.value}</p>{current && date.next_scheduled_on && current.due_on >= today && alert.label !== 'Alerts paused' && alert.label !== 'Alerts off' && <p className="hint">Delivery follows your account timezone and queue availability.</p>}{alert.label === 'Alerts paused' && item.alert_delivery_paused && <Link className="text-button" href={(demo ? '/demo' : '') + '/settings/alerts'}>Alert Options →</Link>}</div>
    </div>
    {current && current.due_on<today && <p className="alert error spaced">Check whether a renewal, payment or service still needs attention.</p>}
    <p className="hint spaced">Selected timings: {date.offsets.map(timingLabel).join(' · ')}. Delivery follows your alert coverage and account preferences.</p>
    {date.recurrence_months && <div className="spaced"><p><strong>Frequency:</strong> {recurrenceFrequencies.find(f => f.months === date.recurrence_months)?.label}</p><p><strong>End date:</strong> {date.recurrence_ends_on ? formatDate(date.recurrence_ends_on) : 'No end date'}</p><p className="hint">The schedule continues automatically. Dates not marked done remain unconfirmed in history; they are never marked paid automatically. Edit the date to change or stop recurrence.</p></div>}
    {date.payment_amount_minor != null && <p className="spaced"><strong>{date.recurrence_months ? 'Payment per cycle:' : 'Payment amount:'}</strong> {formatMoney(date.payment_amount_minor)}</p>}
    {selected && intent.get('action') === 'complete' && intent.get('due') !== current?.due_on && <p className="alert info spaced">This alert was for an earlier date. Review the current date and history before marking anything done.</p>}
    {edit && <DateEditor item={item} date={date} demo={demo} onClose={()=>setEdit(false)}/>}
    {current&&!done&&<button className="button secondary spaced" onClick={()=>{setDone(true);setNext('');}}>{date.kind === 'warranty' ? 'Finish tracking this warranty' : date.kind === 'service' ? 'Mark service done' : date.kind === 'expiration' || date.kind === 'registration' || date.kind === 'insurance' ? 'Mark renewed / completed' : 'Mark done'}</button>}
    {done&&<form onSubmit={complete} className="spaced"><fieldset disabled={busy}><div className="field-grid"><label>Completed on<input required type="date" max={today} value={completed} onChange={e=>setCompleted(e.target.value)}/></label>{!date.recurrence_months && date.kind !== 'warranty' && <label>Next date (optional)<input type="date" value={next} onChange={e=>setNext(e.target.value)}/></label>}</div><p className="hint">{date.recurrence_months && current && date.recurrence_anchor ? 'Next scheduled date: ' + (nextRecurringDate(date.recurrence_anchor, current.due_on, date.recurrence_months, date.recurrence_ends_on || null) || 'None · this is the final cycle.') : date.kind === 'warranty' ? 'This finishes tracking your warranty. Coverage does not renew automatically.' : ['expiration','registration','insurance'].includes(date.kind) ? 'Use the confirmed date on your renewed document. Leave next date empty to finish.' : 'Add your next confirmed date, or leave it empty to finish.'}</p>{date.kind==='service'&&date.interval_months&&<div className="presets"><button type="button" onClick={()=>setNext(addMonths(completed,date.interval_months!))}>From completion: {date.interval_months} months</button>{current&&<button type="button" onClick={()=>setNext(addMonths(current.due_on,date.interval_months!))}>Keep original schedule</button>}</div>}<div className="form-actions"><button type="button" className="button secondary" onClick={()=>setDone(false)}>Cancel</button><button className="button primary">Confirm completion</button></div></fieldset></form>}
    {error&&<p className="alert error" role="alert">{error}</p>}
    <details className="spaced"><summary>History ({history.length} {history.length===1?'cycle':'cycles'})</summary><ul>{[...history].sort((a,b)=>b.cycle-a.cycle).map(o=><li key={o.id}>{formatDate(o.due_on)} · {o.status === 'unconfirmed' ? 'Past due · not marked done' : o.status}{o.completed_on?' on '+formatDate(o.completed_on):''}</li>)}</ul>{hasOlder&&!demo&&<button className="text-button" disabled={busy} onClick={()=>void older()}>Load older history</button>}</details></section>;
}
export function ItemDetail({item,today,demo=false}:{item:ItemWithDetails;today:string;demo?:boolean}){
  const router=useRouter(), [add,setAdd]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false), base=demo?'/demo':'';
  async function change(remove=false){if(demo){setError('Sample reminders cannot be changed.');return;}if(remove&&!confirm('Permanently remove this reminder, its dates and attached files?'))return;setBusy(true);try{const r=remove?await deleteItem(item.id):await archiveItem(item.id,item.revision,!item.archived_at);if(r.error)throw new Error(r.error);if(remove)router.push('/items');router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to update.');}finally{setBusy(false);}}
  return <><Link className="back-link" href={base+'/items'}>← Reminders</Link><div className="page-heading"><div><div className="detail-type"><ReminderIcon template={item.template_key} category={item.category} preset={item.reminder_preset}/><span className="eyebrow">{(getReminderPreset(item.template_key, item.reminder_preset || undefined) || templates[item.template_key]).label}</span></div><h1>{item.product_name}</h1><p>{item.archived_at?'Archived · alerts paused':'Little things, safely kept.'}</p></div><Link className="button secondary" href={base+(item.template_key==='receipt'?'/purchases/':'/items/')+item.id+'/edit'}>Edit details</Link></div><CoverageControl item={item} demo={demo} /><div className="detail-grid"><section><div className="panel"><h2>Important dates</h2><p className="section-description">An alert is optional. Each date keeps its own history.</p>{!item.dates.length&&<p className="spaced">No dates yet. Add one whenever you’re ready.</p>}{item.dates.length<10&&!add&&<button className="button secondary spaced" onClick={()=>setAdd(true)}>Add a date</button>}</div>{add&&<DateEditor item={item} demo={demo} onClose={()=>setAdd(false)}/ >}{item.dates.map(d=><DateCard key={d.id+'-'+d.revision} item={item} date={d} today={today} demo={demo}/>)}</section><aside><section className="panel"><h2>Your notes</h2><p className="notes-text spaced">{item.notes||'Nothing added yet.'}</p>{item.template_key==='receipt'&&<Link className="text-button spaced" href={base+'/purchases/'+item.id}>Receipt & purchase details →</Link>}</section>{templates[item.template_key].files&&<ItemDocuments id={item.id} kind={item.template_key === 'receipt' ? 'receipt' : item.template_key === 'aircon' ? 'service' : 'vehicle'} documents={item.documents} demo={demo}/>}<div className="danger-zone"><h3>{item.archived_at?'Restore this reminder':'Archive or remove'}</h3><p>Archiving pauses alerts and keeps your history. Active Reminders are unlimited; attached files still use storage.</p><button className="button secondary" disabled={busy} onClick={()=>void change()}>{item.archived_at?'Restore reminder':'Archive reminder'}</button><button className="text-button spaced" disabled={busy} onClick={()=>void change(true)}>Delete reminder and files</button>{error&&<p className="alert error" role="alert">{error}</p>}</div></aside></div></>;
}
