'use client';
import Link from 'next/link';
import { useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { addMonths, formatDate } from '@/lib/domain';
import { templates } from '@/features/templates';
import { currentOccurrence, type ItemWithDetails, type DateWithDetails } from '@/features/items/domain';
import { dateHistory, saveDate, completeDate, archiveItem, deleteItem } from '@/features/items/actions';
import { DateFields, initialDate, type DateInput } from './date-fields';
import { CoverageControl } from './reminder-management';
import { ItemDocuments } from './item-documents';
function DateEditor({ item, date, demo, onClose }: { item: ItemWithDetails; date?: DateWithDetails; demo: boolean; onClose: () => void }) {
  const router=useRouter(), id=useRef(date?.id || '');
  const [value,setValue]=useState<DateInput>(date ? { kind:date.kind,label:date.label,due_on:currentOccurrence(date)?.due_on || '',reminders_enabled:date.reminders_enabled,offsets:date.offsets,interval_months:date.interval_months } : initialDate(item.template_key));
  const [error,setError]=useState(''), [busy,setBusy]=useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); if(demo){ setError('This preview does not store changes. Sign in to save your dates.'); return; } setBusy(true);setError(''); try { id.current ||= crypto.randomUUID(); const r=await saveDate(id.current,item.id,date?.revision || 0,value);if(r.error) throw new Error(r.error);onClose();router.refresh(); }catch(e){setError(e instanceof Error ? e.message : 'Unable to save.');}finally{setBusy(false);} }
  return <form onSubmit={submit} className="panel spaced"><fieldset disabled={busy}><h3>{date ? 'Edit date & reminders' : 'Add an important date'}</h3><DateFields template={item.template_key} value={value} onChange={setValue}/>{error && <p className="alert error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">{busy ? 'Saving…' : 'Save date'}</button></div></fieldset></form>;
}
function DateCard({ item, date, today, demo }: { item:ItemWithDetails;date:DateWithDetails;today:string;demo:boolean }) {
  const router=useRouter(), current=currentOccurrence(date), [edit,setEdit]=useState(false), [done,setDone]=useState(false), [completed,setCompleted]=useState(today), [next,setNext]=useState(''), [error,setError]=useState(''), [busy,setBusy]=useState(false);
  const [history,setHistory]=useState(date.occurrences),[hasOlder,setHasOlder]=useState(date.occurrences.length===20);
  async function older(){setBusy(true);try{const rows=await dateHistory(date.id,Math.min(...history.map(o=>o.cycle)));setHistory(h=>[...h,...rows]);setHasOlder(rows.length===20);}catch{setError('Unable to load older history.');}finally{setBusy(false);}}
  async function complete(e:React.FormEvent){e.preventDefault();if(demo){setError('This preview does not store changes.');return;}setBusy(true);setError('');try{const r=await completeDate(date.id,date.revision,completed,next);if(r.error)throw new Error(r.error);setDone(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to complete.');}finally{setBusy(false);}}
  return <section className="panel spaced" id={'date-'+date.id}><div className="section-heading"><h2>{date.label}</h2><button className="text-button" onClick={()=>setEdit(!edit)}>{edit?'Close editor':'Edit'}</button></div><p className="expiry-big">{current ? formatDate(current.due_on) : 'Completed — no next date'}</p>{current && current.due_on<today && <p className="alert error spaced">{['warranty','expiration'].includes(date.kind)?'Expired':'Overdue'} — check whether a renewal or service is needed.</p>}<p className="hint spaced">{item.archived_at?'Archived — emails paused.':current&&date.reminders_enabled&&item.coverage==='covered'?'Email reminders selected: '+date.offsets.map(o=>o.value+' '+o.unit).join(', ')+' before. Delivery also follows your account preferences.': 'Email reminders are off or there is no upcoming date.'}{date.reminder_disabled_reason==='plan_limit'?' Paused because of your plan limit.':''}</p>
    {date.next_scheduled_on && <p className="hint spaced">Next scheduled email: {formatDate(date.next_scheduled_on)}. Delivery time follows your account timezone and queue availability.</p>}
    {edit && <DateEditor item={item} date={date} demo={demo} onClose={()=>setEdit(false)}/>}
    {current&&!done&&<button className="button secondary spaced" onClick={()=>{setDone(true);setNext('');}}>Mark {date.kind==='service'?'service done':'done / renewed'}</button>}
    {done&&<form onSubmit={complete} className="spaced"><fieldset disabled={busy}><div className="field-grid"><label>Completed on<input required type="date" max={today} value={completed} onChange={e=>setCompleted(e.target.value)}/></label><label>Next date (optional)<input type="date" value={next} onChange={e=>setNext(e.target.value)}/></label></div><p className="hint">Use the new expiry printed on the renewed document. Leave next date empty to finish without another reminder.</p>{date.kind==='service'&&date.interval_months&&<div className="presets"><button type="button" onClick={()=>setNext(addMonths(completed,date.interval_months!))}>From completion: {date.interval_months} months</button>{current&&<button type="button" onClick={()=>setNext(addMonths(current.due_on,date.interval_months!))}>Keep original schedule</button>}</div>}<div className="form-actions"><button type="button" className="button secondary" onClick={()=>setDone(false)}>Cancel</button><button className="button primary">Confirm completion</button></div></fieldset></form>}
    {error&&<p className="alert error" role="alert">{error}</p>}
    <details className="spaced"><summary>History ({history.length} {history.length===1?'cycle':'cycles'})</summary><ul>{[...history].sort((a,b)=>b.cycle-a.cycle).map(o=><li key={o.id}>{formatDate(o.due_on)} · {o.status}{o.completed_on?' on '+formatDate(o.completed_on):''}</li>)}</ul>{hasOlder&&!demo&&<button className="text-button" disabled={busy} onClick={()=>void older()}>Load older history</button>}</details></section>;
}
export function ItemDetail({item,today,demo=false}:{item:ItemWithDetails;today:string;demo?:boolean}){
  const router=useRouter(), [add,setAdd]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false), base=demo?'/demo':'';
  async function change(remove=false){if(demo){setError('Sample items cannot be changed.');return;}if(remove&&!confirm('Permanently remove this item, its dates and attached files?'))return;setBusy(true);try{const r=remove?await deleteItem(item.id):await archiveItem(item.id,item.revision,!item.archived_at);if(r.error)throw new Error(r.error);if(remove)router.push('/items');router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to update.');}finally{setBusy(false);}}
  return <><Link className="back-link" href={base+'/items'}>← My items</Link><div className="page-heading"><div><div className="eyebrow">{templates[item.template_key].label}</div><h1>{item.product_name}</h1><p>{item.archived_at?'Archived · reminders paused':'Little things, safely kept.'}</p></div><Link className="button secondary" href={base+(item.template_key==='receipt'?'/purchases/':'/items/')+item.id+'/edit'}>Edit details</Link></div><CoverageControl item={item} demo={demo} /><div className="detail-grid"><section><div className="panel"><h2>Important dates</h2><p className="section-description">A reminder is optional. Each date keeps its own history.</p>{!item.dates.length&&<p className="spaced">No dates yet. Add one whenever you’re ready.</p>}{item.dates.length<10&&!add&&<button className="button secondary spaced" onClick={()=>setAdd(true)}>Add a date</button>}</div>{add&&<DateEditor item={item} demo={demo} onClose={()=>setAdd(false)}/ >}{item.dates.map(d=><DateCard key={d.id+'-'+d.revision} item={item} date={d} today={today} demo={demo}/>)}</section><aside><section className="panel"><h2>Your notes</h2><p className="notes-text spaced">{item.notes||'Nothing added yet.'}</p>{item.template_key==='receipt'&&<Link className="text-button spaced" href={base+'/purchases/'+item.id}>Receipt & purchase details →</Link>}</section>{templates[item.template_key].files&&<ItemDocuments id={item.id} kind={item.template_key === 'receipt' ? 'receipt' : item.template_key === 'aircon' ? 'service' : 'vehicle'} documents={item.documents} demo={demo}/>}<div className="danger-zone"><h3>{item.archived_at?'Restore this item':'Archive or remove'}</h3><p>Archiving pauses reminders and keeps your history. Saved items are unlimited; attached files still use storage.</p><button className="button secondary" disabled={busy} onClick={()=>void change()}>{item.archived_at?'Restore item':'Archive item'}</button><button className="text-button spaced" disabled={busy} onClick={()=>void change(true)}>Delete item and files</button>{error&&<p className="alert error" role="alert">{error}</p>}</div></aside></div></>;
}
