import Link from 'next/link';
import { formatDate, formatMoney } from '@/lib/domain';
import { amountLabels, type PaymentPlan } from '@/features/items/insights';
import { PaymentTotals } from './household-insights';
import styles from './household-insights.module.css';
export function HouseholdPaymentPlan({plan,base='',paged=false}:{plan:PaymentPlan;base?:string;paged?:boolean}) {
  const last=plan.rows.at(-1);
  return <><Link className="back-link" href={base+'/dashboard'}>← Household overview</Link><div className="page-heading"><div><h1>Payments to plan for</h1><p>{formatDate(plan.today,true)} to {formatDate(plan.ends_on,true)} · PHP · {plan.total} saved or projected payments</p></div></div><section className={'panel '+styles.card}><PaymentTotals plan={plan}/><p className={styles.footer}>Amounts cover the whole account. Overdue and completed occurrences are excluded. Repeating schedules may project another date within this window. These projections are plans, not confirmed bills or payments.</p></section><ol className={styles.paymentList}>{plan.rows.map(row=><li className={styles.paymentRow} key={row.date_id+row.due_on}><div><Link className="text-button" href={base+'/items/'+row.item_id+'#date-'+row.date_id}><strong>{row.product_name}</strong></Link><p>{row.label} · {formatDate(row.due_on)}{row.projected?' · Projected from saved schedule':''}</p></div><div className={styles.amount}><strong>{row.amount_minor==null?'Amount not saved':formatMoney(row.amount_minor)}</strong><p>{amountLabels[row.certainty]}</p>{row.occurrence_id&&<Link className="text-button spaced" href={base+'/items/'+row.item_id+'?'+new URLSearchParams({date:row.date_id,action:'amount'})+'#date-'+row.date_id}>Review amount</Link>}</div></li>)}</ol>{!plan.rows.length&&<p className="panel spaced">{paged?'No more payment dates in this window.':'No payments saved for the next 30 days.'}</p>}<div className="form-actions">{paged&&<Link className="button secondary" href={base+'/items/payments'}>First page</Link>}{plan.has_more&&last&&<Link className="button secondary" href={base+'/items/payments?'+new URLSearchParams({before:last.due_on,id:last.date_id})}>Next page →</Link>}</div></>;
}
