import Link from 'next/link';
import { ArrowRight, CalendarDays, ChartPie, Lightbulb, ReceiptText, Sparkles } from 'lucide-react';
import { formatDate, formatMoney } from '@/lib/domain';
import { formatTotal, paymentTotal } from '@/features/items/insights';
import { checkupInsights, spendingCategories, spendingCategoryLabel, spendingShare, type SpendingCheckup } from '@/features/premium/checkup';
import { premiumProducts } from '@/features/premium/products';
import { PaymentTotals } from './household-insights';
import { ItemIdentityIcon } from './reminder-icon';
import styles from './spending-checkup.module.css';

export function SpendingCheckupInvitation() {
 return <><Link className="back-link" href="/dashboard">← Household overview</Link>
   <div className="page-heading"><div><span className="eyebrow">KEEPLY PREMIUM</span><h1>Your 30-Day Spending Checkup</h1><p>See which upcoming period needs the most preparation and what’s driving your saved costs.</p></div></div>
   <section className={styles.invitation} aria-labelledby="checkup-invitation-heading"><Sparkles size={30} aria-hidden="true"/><div><h2 id="checkup-invitation-heading">Turn your saved expenses into a clearer plan</h2><p>Premium brings your highest-cost period, household category breakdown, and a practical planning takeaway into one checkup.</p><p>Your 30-day calendar, spending totals, amount editing, and payment actions stay available with Free.</p><p className={styles.price}>{formatMoney(premiumProducts.premium_30.amount)} for 30 days · No automatic renewal</p><div className="hero-actions spaced"><Link className="button primary" href="/demo/checkup">Explore a sample account <ArrowRight size={16} aria-hidden="true"/></Link><Link className="button secondary" href="/settings/billing">See Premium plans</Link><Link className="text-button" href="/items/payments">View my Free payment plan</Link></div></div></section>
 </>;
}

export function SpendingCheckupView({plan,demo=false,paged=false}:{plan:SpendingCheckup;demo?:boolean;paged?:boolean}) {
 const base=demo?'/demo':'',insights=checkupInsights(plan),highest=insights?.highest,total=paymentTotal(plan);
 const href=(filter:{week?:string|null;category?:string|null;before?:string;id?:string}={})=>{
   const query=new URLSearchParams(Object.entries(filter).filter((entry):entry is [string,string]=>Boolean(entry[1])));
   return base+'/checkup'+(query.size?'?'+query:'')+'#checkup-expenses';
 };
 const categories=[...plan.categories].sort((a,b)=>BigInt(a.total_minor)===BigInt(b.total_minor)?spendingCategories.indexOf(a.category)-spendingCategories.indexOf(b.category):BigInt(a.total_minor)>BigInt(b.total_minor)?-1:1);
 const selectedWeek=plan.weeks.find(week=>week.starts_on===plan.week),last=plan.rows.at(-1);
 const selection=[selectedWeek?`${formatDate(selectedWeek.starts_on,true)} to ${formatDate(selectedWeek.ends_on,true)}`:null,plan.category?spendingCategoryLabel(plan.category):null].filter(Boolean).join(' · ');
 return <><Link className="back-link" href={base+'/dashboard'}>← Household overview</Link>
   <div className="page-heading"><div><span className="eyebrow">{demo?'PREMIUM SAMPLE · FICTIONAL EXPENSES':'KEEPLY PREMIUM'}</span><h1>Your 30-Day Spending Checkup</h1><p>Next 30 days · {formatDate(plan.today,true)} to {formatDate(plan.ends_on,true)}</p></div></div>
   <div className={styles.actions}><Link href={base+'/items/payments'} className="button secondary">Review amounts and payments</Link><Link href={base+'/planner?days=90'} className="text-button">See my household outlook <ArrowRight size={16} aria-hidden="true"/></Link></div>
   <div className={styles.overview}>
     <section className={styles.card} aria-labelledby="checkup-total-heading"><h2 id="checkup-total-heading"><ReceiptText size={21} aria-hidden="true"/>Your Total Household Spending</h2><p className={styles.muted}>Based on the expenses you&apos;ve added to Keeply.</p><PaymentTotals plan={plan}/><p className={styles.muted}>{plan.total} upcoming {plan.total===1?'expense':'expenses'}. Paid, completed, and overdue dates are excluded.</p></section>
     <section className={styles.takeaway} aria-labelledby="checkup-takeaway-heading"><Lightbulb size={24} aria-hidden="true"/><h2 id="checkup-takeaway-heading">{insights?'Your planning takeaway':'Build a useful checkup'}</h2>
       {highest&&insights?<><p className={styles.takeawayText}>{insights.ties>1?`Review ${formatDate(highest.starts_on,true)} to ${formatDate(highest.ends_on,true)}. It shares the highest recorded costs with ${insights.ties-1} other ${insights.ties===2?'period':'periods'}.`:insights.only_period?`Your recorded costs fall between ${formatDate(highest.starts_on,true)} and ${formatDate(highest.ends_on,true)}. Review these expenses together to prepare for them.`:`Prepare for ${formatDate(highest.starts_on,true)} to ${formatDate(highest.ends_on,true)} first. It contains ${insights.share} of the upcoming costs currently recorded in your plan.`}</p>{plan.unset_count>0&&<p className={styles.muted}>Missing amounts can change this comparison.</p>}<Link href={href({week:highest.starts_on})} className={styles.action}>Review this period <ArrowRight size={16} aria-hidden="true"/></Link></>:<><p className={styles.takeawayText}>{plan.total===0?'Add your first household expense to start building your spending picture.':plan.source_count===1?'Your plan currently includes one household expense. Add your recurring bills and expected costs for a more useful checkup.':plan.confirmed_count+plan.estimated_count+plan.unverified_count===0?'Your upcoming expenses still need amounts. Add estimates to start comparing costs.':'There aren’t enough positive amounts to compare yet. Add more expected costs when you know them.'}</p><Link className={styles.action} href={base+(plan.total===0?'/add?category=bills':'/items/payments')}>{plan.total===0?'Add a household expense':'Review expected costs'} <ArrowRight size={16} aria-hidden="true"/></Link>{!demo&&<p className={styles.muted}>See how a fuller plan works: <Link className="text-button" href="/demo/checkup">Explore a sample account</Link></p>}</>}
     </section>
   </div>
   {highest&&insights&&<div className={styles.analysis}>
     <section className={styles.card} aria-labelledby="checkup-period-heading"><h2 id="checkup-period-heading"><CalendarDays size={21} aria-hidden="true"/>{insights.only_period?'Your costs are grouped together':insights.ties>1?'Joint highest-cost periods':'Highest-cost upcoming period'}</h2><p className={styles.period}>{formatDate(highest.starts_on,true)} to {formatDate(highest.ends_on,true)}</p><p className={styles.highlightAmount}>{formatTotal(highest.total_minor)}</p><p>{insights.share} of recorded upcoming costs · {highest.total} {highest.total===1?'expense':'expenses'}</p>{BigInt(highest.estimated_minor)>0n&&<p className={styles.muted}>{formatTotal(highest.estimated_minor)} is estimated.</p>}{highest.unset_count>0&&<p className={styles.muted}>{highest.unset_count} {highest.unset_count===1?'amount is':'amounts are'} still unknown in this period.</p>}{insights.ties>1&&<p className={styles.muted}>{insights.ties} periods share this total. The earliest is shown.</p>}<Link className={styles.action} href={href({week:highest.starts_on})}>View contributing expenses <ArrowRight size={16} aria-hidden="true"/></Link><p className={styles.note}>Seven-day periods start on {formatDate(plan.today,true)}. The final period ends on {formatDate(plan.ends_on,true)}.</p></section>
     <section className={styles.card} aria-labelledby="checkup-categories-heading"><h2 id="checkup-categories-heading"><ChartPie size={21} aria-hidden="true"/>What’s driving your costs</h2><p className={styles.muted}>Each expense belongs to one household category.</p><ul className={styles.categories}>{categories.map(category=><li key={category.category}><Link href={href({category:category.category})} aria-label={'Review '+spendingCategoryLabel(category.category)+' expenses'}><span><strong>{spendingCategoryLabel(category.category)}</strong>{category.unset_count>0&&<small>{category.unset_count} {category.unset_count===1?'amount':'amounts'} to add</small>}{BigInt(category.estimated_minor)>0n&&<small>{formatTotal(category.estimated_minor)} estimated</small>}</span><span className={styles.categoryAmount}><strong>{category.known_count?formatTotal(category.total_minor):'Amount unknown'}</strong>{category.known_count>0&&<small>{spendingShare(category.total_minor,total)} of recorded costs</small>}</span><ArrowRight size={16} aria-hidden="true"/></Link></li>)}</ul><p className={styles.note}>Shares use recorded amounts, including estimates. Missing amounts are excluded. Shares are rounded.</p></section>
   </div>}
   <section className={styles.expenses} aria-labelledby="checkup-expenses"><div className={styles.listHeading}><div><h2 tabIndex={-1} id="checkup-expenses">{selection||'Expenses in your checkup'}</h2><p className={styles.muted}>{plan.filtered_total} {plan.filtered_total===1?'expense':'expenses'}{selection?' in this selection':' in the full plan'}</p></div>{(selection||paged)&&<Link className="text-button" href={href()}>Show all expenses</Link>}</div>
     <ol className={styles.rows}>{plan.rows.map(row=><li key={row.date_id+':'+row.due_on}><ItemIdentityIcon item={row.identity}/><div className={styles.rowIdentity}><Link href={base+'/items/'+row.item_id+'#date-'+row.date_id}><strong>{row.product_name}</strong></Link><p>{row.label} · {formatDate(row.due_on,true)}</p><small>{spendingCategoryLabel(row.reporting_category)}{row.projected?' · Projected from saved schedule':''}</small></div><div className={styles.rowAmount}><strong>{row.amount_minor==null?'Amount not yet known':formatMoney(row.amount_minor)}</strong><small>{row.amount_minor==null?'Excluded from the total':row.certainty==='estimated'?'Estimated amount':row.certainty==='confirmed'?'Confirmed amount':'Expected amount'}</small></div></li>)}</ol>
     {!plan.rows.length&&<p className={styles.empty}>{plan.filtered_total===0?'No upcoming expenses in this selection.':'No more expenses on this page.'}</p>}
     <div className={styles.actions}>{paged&&<Link className="button secondary" href={href({week:plan.week,category:plan.category})}>First page</Link>}{plan.has_more&&last&&<Link className="button secondary" href={href({week:plan.week,category:plan.category,before:last.due_on,id:last.date_id})}>More expenses <ArrowRight size={16} aria-hidden="true"/></Link>}</div>
   </section>
   {demo&&<p className={styles.note}>This checkup uses fictional sample expenses. Open your own household account to build a checkup from your saved records.</p>}
 </>;
}
