import Link from 'next/link';
import { Brand } from '@/components/brand';
export const metadata = { title: 'Terms', alternates: { canonical: '/terms' } };
export default function TermsPage() { return <><nav className="public-nav"><Brand /><Link href="/pricing">Plans →</Link></nav><main className="legal-page" id="main-content"><h1>Using Keeply</h1><p>Keeply helps you organize receipts, important dates and optional documents.</p>
  {!process.env.SUPPORT_EMAIL && <p className="alert info">Preview terms: operator details, refund handling, and the final terms must be reviewed before accepting customers or payments.</p>}
  <h2>Your account and uploads</h2><p>Use an account you control and upload only documents you have permission to store. Keep your Google account secure. Do not use Keeply to store unlawful content, interfere with the service, or access another person’s information.</p>
  <h2>Purchase and warranty records</h2><p>You are responsible for the accuracy of the details you enter. Keeply does not issue warranties, decide claim eligibility, or extend a seller’s coverage. Keep original documents when the seller requires them.</p>
  <h2>Reminder emails</h2><p>Reminders are optional and depend on the dates and preferences you enter, service availability, and email delivery. Keeply cannot guarantee delivery or that a reminder will arrive before a claim deadline. You remain responsible for confirming deadlines and requirements with the responsible provider.</p>
  <h2>Saved items and reminder slots</h2><p>Free includes unlimited saved items, 3 item reminder slots, and 100 MB of document storage. One item uses one slot for all its enabled dates. Add five slots for ₱29 for 30 days or ₱249 once permanently. File-enabled templates allow up to 6 files per item and 10 MB per file; reminder packs do not increase file storage.</p><p>Payments are individual PayMongo checkouts, verified server-side. No automatic charges. Early renewal extends your current paid period by 30 days; renewal after expiry starts a new 30-day period when verified. On expiry, your oldest selected items keep available coverage, excess selections pause, and all saved items remain accessible. Paused selections resume if capacity returns unless you turn them off. You may change your selections at any time.</p><p>The permanent pack replaces the same five extra slots when upgrading from 30-day access, without an automatic prorated refund. Refunded payments may have their associated benefits revoked. Existing annual paid access and storage are honored through the purchased term. Optional renewal emails can be disabled in Settings.</p>
  <h2>Payment problems</h2><p>If you were charged but your reminder pack has not activated, refresh your billing history and contact support with your order reference. Avoid paying again while a payment is being investigated. Refund requests and disputed payments require review; applicable consumer rights are not excluded.</p>
  <h2>Availability and changes</h2><p>Keep a separate copy of important receipts. Maintenance, provider outages, and storage limits can affect availability. Material changes to plans or these terms should be communicated before they take effect.</p>
  <h2>Support</h2><p>{process.env.SUPPORT_EMAIL ? <a href={'mailto:' + process.env.SUPPORT_EMAIL}>{process.env.SUPPORT_EMAIL}</a> : 'A support contact will be published before public launch.'} See also our <Link href="/privacy">privacy notice</Link>.</p>
</main></>; }
