import Link from 'next/link';
import { Brand } from '@/components/brand';
import { operatorName, supportEmail } from '@/lib/env';
export const metadata = { title: 'Terms', alternates: { canonical: '/terms' } };
export default function TermsPage() { const contact = supportEmail(); return <><nav className="public-nav"><Brand /><Link href="/pricing">Plans →</Link></nav><main className="legal-page" id="main-content"><h1>Using Keeply</h1><p>{operatorName()} provides Keeply to help you organize receipts, important dates and optional documents. For account, payment or privacy questions, contact <a href={'mailto:' + contact}>{contact}</a>.</p>
  {!process.env.SUPPORT_EMAIL && <p className="alert info">Preview terms: operator details, refund handling, and the final terms must be reviewed before accepting customers or payments.</p>}
  <h2>Your account and uploads</h2><p>Use an account you control and upload only documents you have permission to store. Keep your Google account secure. Do not use Keeply to store unlawful content, interfere with the service, or access another person’s information.</p>
  <h2>Purchase and warranty records</h2><p>You are responsible for the accuracy of the details you enter. Keeply does not issue warranties, decide claim eligibility, or extend a seller’s coverage. Keep original documents when the seller requires them.</p>
  <h2>Alerts</h2><p>Alerts are optional and depend on the dates and preferences you enter, service availability, and alert delivery. Keeply cannot guarantee delivery or that an alert will arrive before a claim deadline. Email is the default. SMS is currently unavailable. You remain responsible for confirming deadlines and requirements with the responsible provider.</p>
  <h2>Active Reminders and alert slots</h2><p>Free includes unlimited saved items, 3 alert slots, and 100 MB of document storage. One reminder uses one slot for all its enabled dates. Choose 5–100 extra slots in increments of five, at ₱29 per five slots for 30 days or ₱249 per five slots permanently. File-enabled templates allow up to 6 files per reminder and 10 MB per file; alert packs do not increase file storage.</p><p>Payments are individual PayMongo checkouts, verified server-side. No automatic charges. Early renewal adds a 30-day term after your current prepaid time; the purchased slot count applies to that term; renewal after expiry starts a new 30-day period when verified. On expiry, your oldest selected reminders keep available coverage, excess selections pause, and all saved reminders remain accessible. Paused selections resume if capacity returns unless you turn them off. You may change your selections at any time.</p><p>Permanent slots replace temporary access immediately; additional permanent purchases add slots up to 100 extra slots, without an automatic prorated refund. Refunded payments may have their associated benefits revoked. Existing annual paid access and storage are honored through the purchased term. Optional renewal emails can be disabled in Settings.</p>
  <h2 id="permanent-access">What permanent access means</h2><p>A one-time purchase gives the selected extra alert slots no scheduled expiry and requires no renewal while Keeply operates. It does not promise that the service will operate forever or that third-party delivery will always be available. If Keeply plans to discontinue the service, we will notify affected customers in advance and explain what happens to prepaid access and any applicable refunds.</p>
  <h2 id="payment-problems">Payment help and refund requests</h2><p>If you were charged but your alert pack has not activated, check Payment history in Plan &amp; billing. A pending status means payment has not yet been verified; avoid paying again while it is being checked.</p><p>For a missing activation, suspected duplicate charge or refund request, email <a href={'mailto:' + contact + '?subject=Keeply%20payment%20help'}>{contact}</a> from your account email. Include the order reference from Payment history, the amount and date, and what went wrong. Do not send card numbers, passwords or one-time codes.</p><p>We review the payment with PayMongo and explain the outcome before any access adjustment. Refund requests are reviewed individually; approval is not automatic, and provider processing times vary. A confirmed refund may remove the associated purchased slots. Applicable consumer rights are not excluded.</p>
  <h2>Availability and changes</h2><p>Keep a separate copy of important receipts. Maintenance, provider outages, and storage limits can affect availability. Material changes to plans or these terms should be communicated before they take effect.</p>
  <h2>Support</h2><p><a href={'mailto:' + contact}>{contact}</a> See also our <Link href="/privacy">privacy notice</Link>.</p>
</main></>; }
