import Link from 'next/link';
import { Brand } from '@/components/brand';
import { operatorName, supportEmail } from '@/lib/env';
export const metadata = { title: 'Terms', alternates: { canonical: '/terms' } };
export default function TermsPage() { const contact = supportEmail(); return <><nav className="public-nav"><Brand /><Link href="/pricing">Plans →</Link></nav><main className="legal-page" id="main-content"><h1>Using Keeply</h1><p>{operatorName()} provides Keeply to help you organise household obligations, important dates and optional documents. For account, payment or privacy questions, contact <a href={'mailto:' + contact}>{contact}</a>.</p>
  {!process.env.SUPPORT_EMAIL && <p className="alert info">Preview terms: operator details, refund handling, and the final terms must be reviewed before accepting customers or payments.</p>}
  <h2>Your account and uploads</h2><p>Use an account you control and upload only documents you have permission to store. Keep your Google account secure. Do not use Keeply to store unlawful content, interfere with the service, or access another person’s information.</p>
  <h2>Purchase and warranty records</h2><p>You are responsible for the accuracy of the details you enter. Keeply does not issue warranties, decide claim eligibility, or extend a seller’s coverage. Keep original documents when the seller requires them.</p>
  <h2>Alerts</h2><p>Alerts are optional and depend on the dates and preferences you enter, service availability, and alert delivery. Keeply cannot guarantee delivery or that an alert will arrive before a claim deadline. Email is the default. SMS is currently unavailable. You remain responsible for confirming deadlines and requirements with the responsible provider.</p>
  <h2>Household organisation and Premium</h2><p>Your account includes unlimited saved household items, optional alerts, history, readiness, next-30-day planning and 100 MB of document storage. File-enabled records allow up to 6 files per record and 10 MB per file. Premium adds planning up to a year ahead and monthly costs based on the dates, repeating schedules and amounts you save. Estimates and missing amounts are identified. Keeply does not import bills, connect to banks, make payments or provide a complete household budget.</p><p>Premium costs ₱59 for 30 days or ₱499 for one year. Payments are individual PayMongo checkouts, verified server-side. There are no automatic charges or automatic renewals. New paid time follows any remaining Premium time. After expiry, your saved records, history and core alerts remain available, with planning limited to the next 30 days. Premium planning does not increase file storage.</p><h2>Installation gift</h2><p>Install Keeply and open the installed app while signed in to receive 30 days of full Premium automatically. No card, payment details or notification permission is required. The gift is available once per account across devices and is added after any existing prepaid Premium time. Uninstalling or reinstalling does not grant another gift. The expiry is shown when the gift activates.</p>
  <h2 id="permanent-access">Existing purchases</h2><p>Historical paid access is honoured through its remaining purchased term. Existing permanent alert-slot purchases include household Premium with no scheduled expiry while Keeply operates. This does not promise that the service will operate forever or that third-party delivery will always be available. Existing annual storage allowances remain valid through their purchased term. If Keeply plans to discontinue the service, we will notify affected customers in advance and explain what happens to prepaid access and any applicable refunds. A confirmed refund may remove the associated purchased benefits.</p>
  <h2 id="payment-problems">Payment help and refund requests</h2><p>If you were charged but your Premium has not activated, check Payment history in Plan &amp; billing. A pending status means payment has not yet been verified; avoid paying again while it is being checked.</p><p>For a missing activation, suspected duplicate charge or refund request, email <a href={'mailto:' + contact + '?subject=Keeply%20payment%20help'}>{contact}</a> from your account email. Include the order reference from Payment history, the amount and date, and what went wrong. Do not send card numbers, passwords or one-time codes.</p><p>We review the payment with PayMongo and explain the outcome before any access adjustment. Refund requests are reviewed individually; approval is not automatic, and provider processing times vary. A confirmed refund may remove the associated purchased access. Applicable consumer rights are not excluded.</p>
  <h2>Availability and changes</h2><p>Keep a separate copy of important receipts. Maintenance, provider outages, and storage limits can affect availability. Material changes to plans or these terms should be communicated before they take effect.</p>
  <h2>Support</h2><p><a href={'mailto:' + contact}>{contact}</a> See also our <Link href="/privacy">privacy notice</Link>.</p>
</main></>; }
