import Link from 'next/link';
import { Brand } from '@/components/brand';
import { operatorName, supportEmail } from '@/lib/env';
export const metadata = { title: 'Privacy', alternates: { canonical: '/privacy' } };
export default function PrivacyPage() { return <><nav className="public-nav"><Brand /><Link href="/login">Your account →</Link></nav><main className="legal-page" id="main-content"><h1>Your important things are personal.</h1><p>Keeply stores receipts, optional documents and important dates so you can find them when you need them.</p>
  {!process.env.SUPPORT_EMAIL && <p className="alert info">Preview notice: the operator’s contact details and final retention policy must be completed before public launch.</p>}
  <h2>What we store</h2><p>We use your Google account’s identifier, email address, and name to create your account. We store the reminder details, optional receipts and vehicle documents, important dates, completion history, timezone, optional mobile number and its verification status, and alert preferences you choose to add. If you enable web push, we also store your device’s push subscription endpoint and encryption keys. Payment references and plan dates are stored to manage Premium access.</p>
  <h2>How we use it</h2><p>Your information is used to provide your account, organize reminders, deliver alerts you enable, process plan purchases, and investigate service problems. Keeply does not sell your receipt data or use advertising trackers.</p>
  <h2>Where it goes</h2><p>Supabase provides authentication, PostgreSQL, and private file storage. Vercel hosts the application. Resend processes alert emails, including the reminder name, date label and due date. Optional web push uses the push service provided by your browser, such as Apple, Google or Mozilla. Notification content includes the reminder name, date label and due date, is encrypted for the device, and may appear on your lock screen. Push services process routing metadata. SMS is not currently enabled, and we do not request a phone number for alerts. Google provides sign-in. PayMongo processes payments on its own checkout; Keeply does not receive or store your full card details. These providers may process data outside your country.</p>
  <h2>Private documents</h2><p>Document access requires your account. Download links are temporary and expire after 60 seconds. Anyone you share an unexpired link with may use it, so keep these links private. Images are resized and re-encoded to reduce storage and remove image metadata. PDFs are delivered as downloads.</p>
  <h2>Your choices</h2><p>You can edit or remove reminders, switch off email alerts or web push on each connected device in Alert Options, and request account deletion from Settings. Deletion immediately blocks account access, then a scheduled process removes files and the authentication account. Unfinished reminders are removed after 24 hours; incomplete file uploads expire after two hours unless you retry.</p><p>Transaction references needed for payment reconciliation may remain after account deletion, without a link to your deleted account. Provider records and backup copies are subject to the configured retention periods and provider policies.</p>
  <h2>Feedback and thank-you rewards</h2><p>When you submit feedback, we store its type, summary and optional notes privately with your account for up to 12 months. Keeply operators use it to improve the service. A minimal reward claim record remains for the life of your account to prevent repeat claims. Account deletion removes your linked feedback and claim record. Feedback is not published as a testimonial without separate permission.</p>
  <h2>Calculator reactions</h2><p>If you choose an emoji on the LTO calculator, we save the reaction in private daily totals. A random submission receipt prevents retries from counting twice and is removed after 400 days by scheduled maintenance; daily totals remain. We do not attach your plate number, account, IP address or referrer to a reaction. Your browser remembers your choice locally to discourage repeat submissions. Clearing browser storage allows another reaction; these counts do not represent unique visitors.</p>
  <h2>Cookies and service logs</h2><p>Keeply uses authentication cookies to keep you signed in. Operational logs record failures and job counts; application logging avoids receipt contents, private file links, and full payment payloads.</p>
  <h2>Optional product measurement</h2><p>If you enable Help improve Keeply in Settings, we record reminder type and counts of saves, alert opt-ins, completions, Premium previews, feature use and verified Premium activations, linked to your account. Premium events include only the screen, planning horizon and kind of insight used. These events do not contain household amounts, reminder names, identity numbers, files or due dates. Raw events expire after 90 days; weekly aggregate return rates remain without an account link. A per-account save counter prevents repeated first-save counting. If a presentation experiment is enabled, a stable account assignment keeps the same presentation across visits. This minimal assignment remains until you turn measurement off or delete your account. Prices, features and trial rules are the same in both presentations. Turning measurement off deletes your linked measurement data. Optional public-page counts are daily totals without cookies, IP addresses, visitor identifiers or referrer URLs.</p>
  <h2 id="contact">Contact</h2><p>{operatorName()} can be reached at <a href={'mailto:' + supportEmail()}>{supportEmail()}</a> for privacy requests and support. For payment help, see <Link href="/terms#payment-problems">how to request a payment review or refund</Link>.</p>
</main></>; }
