import { TrackerPage } from '@/components/tracker-page';
const title = 'Receipt & Warranty Tracker for Home Purchases';
const description = 'Track appliance and purchase warranties with Keeply. Keep receipts, store details and warranty dates together, with optional expiry alerts and a free account.';
export const metadata={title,description,alternates:{canonical:'/warranty-tracker'},openGraph:{title:title+' · Keeply',description,url:'/warranty-tracker',siteName:'Keeply',locale:'en_PH',type:'website'},twitter:{card:'summary_large_image',title:title+' · Keeply',description}};
export default function Page(){return <TrackerPage page="warranty-tracker" title="Receipts and warranties, ready when you need them." intro="Track purchase and appliance warranties with Keeply. Keep your proof of purchase, store details and coverage dates together, so there’s less searching later." example="Your Sony headphones have 11 days of warranty left. Open the saved item to find the store details, receipt and coverage notes." sections={[
{id:'warranties',title:'Know when your warranty ends',body:'Start with a product name. Add the warranty start and duration, or enter its expiration date directly. Optional alerts start with 30, 7 and 1 day before expiry; change the timings on the reminder’s date page.',cta:'Add my warranty',href:'/add/receipt?focus=warranty'},
{id:'receipts',title:'Keep the receipt, even without a warranty',body:'Upload a photo or PDF, or save the purchase first and attach it later. Add the merchant, purchase date and price in pesos when useful. Keeply is for retrieval and alerts; it does not prepare accounting books or tax returns.',cta:'Save my receipt',href:'/add/receipt'},
{id:'aircon-care',title:'When should you clean your aircon?',body:'Separate routine filter care from professional servicing. Compare schedules by daily use, published cleaning prices and a checklist for the technician’s visit.',cta:'Read the aircon cleaning guide',href:'/aircon-cleaning-schedule'},
{id:'appliances',title:'Give appliance paperwork a home',body:'Keep the washing machine’s receipt, warranty paperwork and optional serial number with its purchase. For recurring aircon cleaning, use the separate maintenance template and the interval advised by your technician.',cta:'Keep my appliance receipt',href:'/add/receipt?category=appliances'}
]} checklist={['A useful product name is the only required purchase detail.','If adding a warranty, check its actual expiration or start date and duration.','Optional files: JPG, PNG, WebP or PDF, up to 10 MB each and 6 files per reminder.','Choose an advance alert, a due-day alert, or both for your warranty dates.']} limitations="Your seller’s or manufacturer’s terms determine coverage and claim requirements. Keeply records the dates you provide; storing a receipt does not guarantee a successful claim."/>;}
